/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.controller.ApartadosController;
import com.ortometh.model.Apartados;
import com.ortometh.model.UsuarioLogin;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class AbonosView extends javax.swing.JFrame {

    ApartadosController ac = new ApartadosController();
    Calendar fecha = Calendar.getInstance();
    private int d = 0;
    private int id_abono;
    private int idApartado;
    private double resto;
    private double total;

    //variable de usuario
    public static UsuarioLogin usuario;

    /**
     * Creates new form AbonosView
     */
    public AbonosView() {
        initComponents();
    }

    public AbonosView(int idApartado, double resto, double total, UsuarioLogin user) {
        initComponents();
        this.idApartado = idApartado;
        this.usuario = user;
        lblFecha.setText(fecha.get(Calendar.DATE) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR));
        lblRestante.setText(String.valueOf(resto));
        lblTotal.setText(String.valueOf(total));
        this.resto = resto;
        this.total = total;
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
        this.setTitle("Abonos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAbono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        btnAbonar = new com.ortometh.RSbuttom.RSButtonMetro();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblRestante = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 98, 158));
        jLabel1.setText("ABONOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 11, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(67, 98, 158));
        jLabel5.setText("ABONO: *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAbonoKeyPressed(evt);
            }
        });
        jPanel1.add(txtAbono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("CAMBIO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        lblCambio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lblCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 170, 20));

        btnAbonar.setBackground(new java.awt.Color(231, 50, 116));
        btnAbonar.setText("ABONAR");
        btnAbonar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnAbonar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnAbonar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAbonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(67, 98, 158));
        jLabel8.setText("RESTANTE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(67, 98, 158));
        jLabel9.setText("TOTAL:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        lblRestante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lblRestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 170, 20));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 150, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(67, 98, 158));
        jLabel12.setText("FECHA:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarActionPerformed
        if (txtAbono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos obligatorios", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            if (resto == 0 || resto == 0.0 || resto == 0.00) {
                JOptionPane.showMessageDialog(null, "El apartado ya esta totalmente pagado", "Advertencia", JOptionPane.YES_OPTION);
            } else {
                double abono = Double.parseDouble(txtAbono.getText());
                ac.abonar(idApartado, abono, usuario.getIdUserLog());
                double cambio = 0;
                if (abono > resto) {
                    cambio = abono - resto;
                }
                lblCambio.setText(String.valueOf(cambio));
                lblRestante.setText(ac.restante(idApartado));
                txtAbono.setText("");
                resto = Double.parseDouble(ac.restante(idApartado));
            }
        }
        txtAbono.requestFocus();
    }//GEN-LAST:event_btnAbonarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String clave = ac.claveApartado(idApartado);
        ApartadosView ca = new ApartadosView(clave, 0, usuario);
        ca.setVisible(true);
        ca.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void txtAbonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbonoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtAbono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos obligatorios", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            if (resto == 0 || resto == 0.0 || resto == 0.00) {
                JOptionPane.showMessageDialog(null, "El apartado ya esta totalmente pagado", "Advertencia", JOptionPane.YES_OPTION);
            } else {
                double abono = Double.parseDouble(txtAbono.getText());
                ac.abonar(idApartado, abono, usuario.getIdUserLog());
                double cambio = 0;
                if (abono > resto) {
                    cambio = abono - resto;
                }
                lblCambio.setText(String.valueOf(cambio));
                lblRestante.setText(ac.restante(idApartado));
                txtAbono.setText("");
                resto = Double.parseDouble(ac.restante(idApartado));
            }
        }
        txtAbono.requestFocus();
        }
    }//GEN-LAST:event_txtAbonoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbonosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbonosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbonosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbonosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbonosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnAbonar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblRestante;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtAbono;
    // End of variables declaration//GEN-END:variables
}
