/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.Dao.ApartadosDaoImpl;
import com.ortometh.controller.ApartadosController;
import com.ortometh.model.Apartados;
import com.ortometh.model.UsuarioLogin;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class ApartadosView extends javax.swing.JFrame {

    ApartadosController apartadosController = new ApartadosController();
    ApartadosDaoImpl dao = new ApartadosDaoImpl();

    String claveA;
    int proveedor;
    String cliente;
    String doctor;
    String clinica;
    double costo;
    String fecha;
    String numeroCuarto;
    String abono;
    double resto;
    String observaciones;
    String cambio;
    int idApartado;
    int d = 0;
    //variable de usuario
    public static UsuarioLogin usuario;

    /**
     * Creates new form AbonosView
     */
    public ApartadosView() {
        initComponents();
    }

    public ApartadosView(String clave, int d, UsuarioLogin usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        this.claveA = clave;
//        apartadosController.consultarProveedores(cbProveedor);
        idApartado = Integer.parseInt(apartadosController.idApartado(clave));
        apartadosController.consultarAbonos(jTable1, idApartado);
        apartadosController.listProductos(jTableProductos, idApartado);
        datos();
        if (d == 0) {
            rellenar();
            bloquear();
        } else if (d == 1) {
            Calendar fecha = Calendar.getInstance();
            lblFecha.setText(fecha.get(Calendar.DATE) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR));
            lblApartado.setText(clave);
            String total = apartadosController.restante(idApartado);
            lblResto.setText(total);
            lblCosto.setText(total);
        }
        this.d = d;
        txtCliente.requestFocus();
        txtObservaciones.setLineWrap(true);
        txtObservaciones.setWrapStyleWord(true);
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
        this.setTitle("Informacion del Apartado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCuarto = new javax.swing.JTextField();
        txtClinica = new javax.swing.JTextField();
        txtDoctor = new javax.swing.JTextField();
        lblResto = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblApartado = new javax.swing.JLabel();
        btnAbonar = new com.ortometh.RSbuttom.RSButtonMetro();
        lblFecha = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("ABONOS"));

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col)
            {
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 640, 200));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(67, 98, 158));
        jLabel3.setText("APARTADOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 98, 158));
        jLabel4.setText("APARTADO:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("NOMBRE DEL CLIENTE: *");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(67, 98, 158));
        jLabel9.setText("TOTAL:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(67, 98, 158));
        jLabel10.setText("OBSERVACIONES: *");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 350, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(67, 98, 158));
        jLabel15.setText("RESTO:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        jPanel2.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(67, 98, 158));
        jLabel7.setText("NOMBRE DEL DOCTOR:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(67, 98, 158));
        jLabel8.setText("NOMBRE DE LA CLÍNICA:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(67, 98, 158));
        jLabel12.setText("NUMERO DE CUARTO:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));
        jPanel2.add(txtCuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 160, -1));
        jPanel2.add(txtClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 160, -1));
        jPanel2.add(txtDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 160, -1));

        lblResto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(lblResto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 160, 20));

        lblCosto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(lblCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 160, 20));
        jPanel2.add(lblApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, 20));

        btnAbonar.setBackground(new java.awt.Color(231, 50, 116));
        btnAbonar.setText("ABONAR");
        btnAbonar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnAbonar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnAbonar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAbonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAbonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 110, 30));

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(67, 98, 158));
        jLabel11.setText("FECHA DE APARTADO:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 380, 370));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("PRODUCTOS"));

        jTableProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col)
            {
                return false;
            }
        };
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableProductos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 640, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ConsultaApartadosView a = new ConsultaApartadosView(usuario);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnAbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarActionPerformed
        if (lblResto.getText().equals("0.0")) {
            JOptionPane.showMessageDialog(null, "El apartado esta totalmente pagado");
        } else {
            if (d == 1) {
                if (txtCliente.getText().isEmpty() || txtObservaciones.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Debe llenar los campos obligatorios", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                } else {
                    agregar();
                    d = 0;
                    idApartado = Integer.parseInt(apartadosController.idApartado(claveA));
                    lblResto.setText(apartadosController.restante(idApartado));
                    bloquear();
                    AbonosView atv = new AbonosView(idApartado, resto, costo, usuario);
                    atv.setVisible(true);
                    atv.setLocationRelativeTo(null);
                    this.dispose();
                }
            } else {
                AbonosView atv = new AbonosView(idApartado, resto, costo, usuario);
                atv.setVisible(true);
                atv.setLocationRelativeTo(null);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAbonarActionPerformed

    private void datos() {
        ArrayList<Apartados> a = dao.consultarApartados(idApartado);
        int rows = a.size();
        for (int i = 0; i < rows; i++) {
            claveA = a.get(i).getClaveApartado();
            cliente = a.get(i).getCliente();
            proveedor = a.get(i).getProveedor();
            doctor = a.get(i).getDoctor();
            clinica = a.get(i).getClinica();
            numeroCuarto = a.get(i).getNumeroCuarto();
            observaciones = a.get(i).getObservaciones();
            fecha = a.get(i).getFecha();
            costo = a.get(i).getCosto();
            resto = a.get(i).getRestantante();
        }

    }

    private void rellenar() {
        lblApartado.setText(claveA);
//        cbProveedor.setSelectedIndex(proveedor);
        txtCliente.setText(cliente);
        txtDoctor.setText(doctor);
        txtClinica.setText(clinica);
        txtCuarto.setText(numeroCuarto);
        lblFecha.setText(fecha);
        lblResto.setText(String.valueOf(resto));
        lblCosto.setText(String.valueOf(costo));
        txtObservaciones.setText(observaciones);
    }

    private void agregar() {
//        proveedor = Integer.parseInt(String.valueOf(cbProveedor.getSelectedIndex()));
        doctor = txtDoctor.getText();
        clinica = txtClinica.getText();
        numeroCuarto = String.valueOf(txtCuarto.getText());
        cliente = txtCliente.getText();
        observaciones = txtObservaciones.getText();
        apartadosController.llenarDatos(idApartado, proveedor, cliente, doctor, clinica, numeroCuarto, observaciones);
    }

    private void bloquear() {
//        cbProveedor.setEnabled(false);
        txtClinica.setEnabled(false);
        txtCuarto.setEnabled(false);
        txtDoctor.setEnabled(false);
        txtCliente.setEnabled(false);
        txtObservaciones.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApartadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApartadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApartadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApartadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApartadosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnAbonar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableProductos;
    public static javax.swing.JLabel lblApartado;
    public static javax.swing.JLabel lblCosto;
    public static javax.swing.JLabel lblFecha;
    public static javax.swing.JLabel lblResto;
    public static javax.swing.JTextField txtCliente;
    public static javax.swing.JTextField txtClinica;
    public static javax.swing.JTextField txtCuarto;
    public static javax.swing.JTextField txtDoctor;
    public static javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
