/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

/**
 *
 * @author bitia
 */
import com.ortometh.Dao.UsuarioDaoImpl;
import com.ortometh.controller.Usuario_Controller;
import com.ortometh.model.Encryption;
import com.ortometh.model.Events;
import com.ortometh.model.UsuarioLogin;
import static com.ortometh.viewMain.MenuView.txtIdUsuarioLogin;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class CambiarContraseñaView extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarPassword
     */
    UsuarioDaoImpl usuarioDaoImpl = new UsuarioDaoImpl();
    Usuario_Controller usuarioController = new Usuario_Controller();
    public static UsuarioLogin usarioLog;
    Events evento = new Events();
    

    public CambiarContraseñaView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtIdUsuarioLogin.setVisible(false);
    }
    
    public CambiarContraseñaView(UsuarioLogin user) { //Utilizamos una sobrecarga de metodos para poder asignarle privilegios al usuario de acuerdo a su rol
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.usarioLog = user; //Variable para acceder a los datos de usuario que inicia sesión
        System.out.println("Id Usuario Login " + user.getIdUserLog());
//        int idUserLogin= user.getIdUserLog();
        txtIdUsuarioLogin.setText(String.valueOf(user.getIdUserLog()));
        txtIdUsuarioLogin.setVisible(false);
        txtNombreUsuario.setText(String.valueOf(user.getNombreUsuario()));
        
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Cambiar Contraseña"); 
    }

    public void limpiar() {
        txtNombreUsuario.setText("");
        txtNuevaContraseña.setText("");
        txtRepetirContraseña.setText("");
        txtContraseñaAntigua.setText("");
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new com.ortometh.RSbuttom.RSButtonMetro();
        btnCancelar = new com.ortometh.RSbuttom.RSButtonMetro();
        jLabel10 = new javax.swing.JLabel();
        txtIdUsuarioLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtContraseñaAntigua = new javax.swing.JPasswordField();
        txtNuevaContraseña = new javax.swing.JPasswordField();
        txtRepetirContraseña = new javax.swing.JPasswordField();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(67, 98, 158));
        jLabel7.setText("Nombre de Usuario");

        jLabel8.setForeground(new java.awt.Color(67, 98, 158));
        jLabel8.setText("Nueva contraseña");

        jLabel9.setForeground(new java.awt.Color(67, 98, 158));
        jLabel9.setText("Repetir contraseña");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 98, 158));
        jLabel1.setText("Actualizar Contraseña");

        btnAceptar.setBackground(new java.awt.Color(231, 50, 116));
        btnAceptar.setText("Aceptar");
        btnAceptar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(231, 50, 116));
        btnCancelar.setText("Cancelar");
        btnCancelar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(67, 98, 158));
        jLabel10.setText("Antigua Contraseña");

        txtIdUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioLoginActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N

        txtNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyTyped(evt);
            }
        });

        txtContraseñaAntigua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseñaAntiguaKeyTyped(evt);
            }
        });

        txtNuevaContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNuevaContraseñaKeyTyped(evt);
            }
        });

        txtRepetirContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRepetirContraseñaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtContraseñaAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(txtNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtRepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtIdUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContraseñaAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtNuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addComponent(txtRepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String passAntigua = new String(txtContraseñaAntigua.getPassword());
        String newPassAntigua = Encryption.sha1(passAntigua);
        String pass = new String(txtNuevaContraseña.getPassword());
        String newPass = Encryption.sha1(pass);
        String pass2 = new String(txtRepetirContraseña.getPassword());
        String repetirPass2 = Encryption.sha1(pass2);
        String nameUser = txtNombreUsuario.getText();

        if (usuarioDaoImpl.ValidarUsuarioBaseDatos(nameUser) == true) {
            if (usuarioDaoImpl.ValidarContraseñaAntiguaBaseDatos(newPassAntigua)) {
                if (newPass.equals(repetirPass2)) {
                    usuarioController.modificarContrasena(nameUser, newPass);
                    JOptionPane.showMessageDialog(null, "Contraseña actualizada correctamente");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Verifique los campos de contraseña nueva");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Contraseña antigua incorrecta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nombre de usuario incorrecto");
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        CambiarContraseñaView actualizarPasswordView = new CambiarContraseñaView();
        this.setVisible(false);
        UsuariosView UsuariosView = new UsuariosView(usarioLog);
        UsuariosView.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIdUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioLoginActionPerformed
    }//GEN-LAST:event_txtIdUsuarioLoginActionPerformed

    private void txtNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyTyped
        evento.textKeyPress(evt);
    }//GEN-LAST:event_txtNombreUsuarioKeyTyped

    private void txtContraseñaAntiguaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaAntiguaKeyTyped
        evento.textVarcharKeyPress(evt);
    }//GEN-LAST:event_txtContraseñaAntiguaKeyTyped

    private void txtNuevaContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevaContraseñaKeyTyped
        evento.textVarcharKeyPress(evt);
    }//GEN-LAST:event_txtNuevaContraseñaKeyTyped

    private void txtRepetirContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRepetirContraseñaKeyTyped
        evento.textVarcharKeyPress(evt);
    }//GEN-LAST:event_txtRepetirContraseñaKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        UsuariosView UsuariosView = new UsuariosView(usarioLog);
        UsuariosView.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseñaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseñaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseñaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContraseñaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContraseñaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.ortometh.RSbuttom.RSButtonMetro btnAceptar;
    public static com.ortometh.RSbuttom.RSButtonMetro btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPasswordField txtContraseñaAntigua;
    public static javax.swing.JTextField txtIdUsuarioLogin;
    private javax.swing.JTextField txtNombreUsuario;
    public static javax.swing.JPasswordField txtNuevaContraseña;
    public static javax.swing.JPasswordField txtRepetirContraseña;
    // End of variables declaration//GEN-END:variables
}
