/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.controller.Categoria_ProductoController;
import com.ortometh.model.Departamento;
import com.ortometh.model.Events;
import com.ortometh.model.UsuarioLogin;
import static com.ortometh.viewMain.ProveedoresView.departamento;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author jacQu
 */
public class CategoriasInsertar extends javax.swing.JFrame {
     Events evento = new Events();
     public static UsuarioLogin usuario;
      public static Departamento departamento;
     Categoria_ProductoController categoria_ProductoController= new Categoria_ProductoController();
    /**
     * Creates new form ProductosCRUD
     */
    public CategoriasInsertar(UsuarioLogin user,Departamento dep) {
        initComponents();
        this.departamento = dep;
        System.out.println("ID:" + departamento.getIdDepartamento() + " Nombre:" + departamento.getNombre());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        tableCategorias.getTableHeader().setReorderingAllowed(false);
        categoria_ProductoController.fillCategorias(tableCategorias);
        this.usuario = user;
        System.out.println("Id Usuario Login " + user.getIdUserLog());
        txtusuarioID.setText(String.valueOf(user.getIdUserLog()));
        btnGuardar.setVisible(false);
        txtActions.setVisible(false);
        txtIdCategoria.setVisible(false);
        txtusuarioID.setVisible(false);
    }

    private CategoriasInsertar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategorias = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnNuevo = new com.ortometh.RSbuttom.RSButtonMetro();
        btnGuardar = new com.ortometh.RSbuttom.RSButtonMetro();
        txtusuarioID = new javax.swing.JTextField();
        txtIdCategoria = new javax.swing.JTextField();
        txtActions = new javax.swing.JTextField();
        btneliminar = new com.ortometh.RSbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "NOMBRE"
            }
        ));
        tableCategorias.getTableHeader().setReorderingAllowed(false);
        tableCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategorias);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 98, 158));
        jLabel4.setText("Categorias");

        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnNuevo.setBackground(new java.awt.Color(231, 50, 116));
        btnNuevo.setText("Nuevo");
        btnNuevo.setColorNormal(new java.awt.Color(231, 50, 116));
        btnNuevo.setColorPressed(new java.awt.Color(38, 86, 186));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(231, 50, 116));
        btnGuardar.setText("Guardar");
        btnGuardar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnGuardar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtusuarioID.setEditable(false);
        txtusuarioID.setBackground(new java.awt.Color(255, 255, 255));

        txtIdCategoria.setEditable(false);
        txtIdCategoria.setBackground(new java.awt.Color(255, 255, 255));

        txtActions.setEditable(false);
        txtActions.setBackground(new java.awt.Color(255, 255, 255));

        btneliminar.setBackground(new java.awt.Color(231, 50, 116));
        btneliminar.setText("Eliminar");
        btneliminar.setColorNormal(new java.awt.Color(231, 50, 116));
        btneliminar.setColorPressed(new java.awt.Color(38, 86, 186));
        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtusuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                    .addComponent(txtActions))
                                .addComponent(jLabel6))
                            .addGap(302, 302, 302)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtusuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ProductosCRUD cRUD = null;
        try {
            cRUD = new ProductosCRUD(usuario,departamento);
        } catch (SQLException ex) {
            Logger.getLogger(CategoriasInsertar.class.getName()).log(Level.SEVERE, null, ex);
        }
        cRUD.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       txtActions.setText("i");
       btnGuardar.setVisible(true);
       txtNombre.setText("");
       txtIdCategoria.setText("");
       btnNuevo.setVisible(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
           if(txtActions.getText().equals("i")){
           if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese un nombre");
        }else{
            String message = categoria_ProductoController.insertarCategoria(txtNombre.getText(), usuario.getIdUserLog());
             JOptionPane.showMessageDialog(null, message, "Registro de Categoria", JOptionPane.INFORMATION_MESSAGE);
             btnNuevo.setVisible(true);
       btnGuardar.setVisible(false);
        }
         txtNombre.setText("");
          txtIdCategoria.setText("");
       categoria_ProductoController.refillCategorias(tableCategorias);
       
      }
      if(txtActions.getText().equals("m")){
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Seleccione una categoria");
        }else{
            String message = categoria_ProductoController.actualizarCategoria(txtNombre.getText(), Integer.parseInt(txtIdCategoria.getText()), usuario.getIdUserLog());
             JOptionPane.showMessageDialog(null, message, "Modificar Categoria", JOptionPane.INFORMATION_MESSAGE);
              btnGuardar.setVisible(false);
              btnNuevo.setVisible(true);
        }
          txtNombre.setText("");
          txtIdCategoria.setText("");
          categoria_ProductoController.refillCategorias(tableCategorias);
         
      }
      
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tableCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoriasMouseClicked
        int fila = tableCategorias.getSelectedRow();
        String id_categoria = tableCategorias.getValueAt(fila, 0).toString();
        String nombre = tableCategorias.getValueAt(fila, 1).toString();
        txtIdCategoria.setText(id_categoria);
        txtNombre.setText(nombre);
        txtActions.setText("m");
        btnGuardar.setVisible(true);
        btnNuevo.setVisible(true);
    }//GEN-LAST:event_tableCategoriasMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int fila = tableCategorias.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una categoria", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            if (txtIdCategoria.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Seleccione un producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                int confirm = JOptionPane.showConfirmDialog(null, "¿Confirma la eliminación?", "Eliminar categoria", JOptionPane.YES_NO_OPTION);
                System.out.println("Opcion: " + confirm);
                if (confirm == 0) {
                    Integer categoria_producto = Integer.parseInt(txtIdCategoria.getText());
                    if (categoria_ProductoController.eliminarProducto(categoria_producto, usuario.getIdUserLog())== true) {
                        JOptionPane.showMessageDialog(null, "Producto eliminado", null, JOptionPane.INFORMATION_MESSAGE);
                        txtNombre.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "No se a podido eliminar", null, JOptionPane.INFORMATION_MESSAGE);
                    }
                    categoria_ProductoController.refillCategorias(tableCategorias);
                }
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoriasInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoriasInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoriasInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriasInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoriasInsertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnGuardar;
    private com.ortometh.RSbuttom.RSButtonMetro btnNuevo;
    private com.ortometh.RSbuttom.RSButtonMetro btneliminar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCategorias;
    private javax.swing.JTextField txtActions;
    private javax.swing.JTextField txtIdCategoria;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtusuarioID;
    // End of variables declaration//GEN-END:variables
}
