/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.controller.Cliente_Controller;
import com.ortometh.controller.ControllerReportes;
import com.ortometh.model.Departamento;
import com.ortometh.model.UsuarioLogin;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jacQu
 */
public class ClientesCRUD extends javax.swing.JFrame {

    Cliente_Controller controllerCliente = new Cliente_Controller();
    public static UsuarioLogin usuario;
    public String formularioPadre;
    public static Departamento departamento;
    /**
     * Creates new form ProductosCRUD
     */
    public ClientesCRUD(UsuarioLogin user, String padre,Departamento dep) throws SQLException {
        initComponents();
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Clientes");
        this.departamento = dep;
        System.out.println("ID:" + departamento.getIdDepartamento() + " Nombre:" + departamento.getNombre());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.usuario = user;
        System.out.println("Id Usuario Login " + user.getIdUserLog());
        txtId_usuario.setText(String.valueOf(usuario.getIdUserLog()));
        //Header de la tabla
        jTable1.getTableHeader().setReorderingAllowed(false);
//        jTable1.getTableHeader().setForeground(Color.blue);
        jTable1.isEditing();
        // Ocultar botones
        btnModificar.setVisible(true);
        btnRecargar.setVisible(true);
        txtId_usuario.setVisible(false);
        txtId_Cliente.setVisible(true);
        formularioPadre = padre;
        controllerCliente.fillTableClienteMoral(jTable1);
        cambio.setVisible(false);
        txtId_Cliente.setVisible(false);
        comboCrud.setSelectedIndex(2);

        if (formularioPadre.equals("r")) {
            btnNuevo.setVisible(false);
            btnModificar.setVisible(false);
            btnEliminar.setVisible(false);
        } else if (formularioPadre.equals("t")) {
            btnReporteFisico.setVisible(false);
            btnReporteMoral.setVisible(false);
            btnReportePorCompras.setVisible(false);
            btnAceptar.setVisible(true);
        }
    }

    private ClientesCRUD() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnNuevo = new com.ortometh.RSbuttom.RSButtonMetro();
        btnEliminar = new com.ortometh.RSbuttom.RSButtonMetro();
        btnModificar = new com.ortometh.RSbuttom.RSButtonMetro();
        btnRecargar = new com.ortometh.RSbuttom.RSButtonMetro();
        txtId_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId_Cliente = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRecargar1 = new com.ortometh.RSbuttom.RSButtonMetro();
        comboCrud = new javax.swing.JComboBox<>();
        cambio = new javax.swing.JTextField();
        btnReporteFisico = new com.ortometh.RSbuttom.RSButtonMetro();
        btnReporteMoral = new com.ortometh.RSbuttom.RSButtonMetro();
        btnReportePorCompras = new com.ortometh.RSbuttom.RSButtonMetro();
        btnAceptar = new com.ortometh.RSbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(1054, 706));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("Clientes");

        btnNuevo.setBackground(new java.awt.Color(231, 50, 116));
        btnNuevo.setText("Nuevo");
        btnNuevo.setColorNormal(new java.awt.Color(231, 50, 116));
        btnNuevo.setColorPressed(new java.awt.Color(38, 86, 186));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(231, 50, 116));
        btnEliminar.setText("Eliminar");
        btnEliminar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnEliminar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(231, 50, 116));
        btnModificar.setText("Modificar");
        btnModificar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnModificar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnRecargar.setBackground(new java.awt.Color(231, 50, 116));
        btnRecargar.setText("Recargar Cliente Fisico");
        btnRecargar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnRecargar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnRecargar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        txtId_usuario.setBackground(new java.awt.Color(240, 240, 240));
        txtId_usuario.setForeground(new java.awt.Color(240, 240, 240));
        txtId_usuario.setBorder(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N

        txtId_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_ClienteActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(231, 50, 116));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 50, 116));
        jLabel1.setText("Buscar");

        btnRecargar1.setBackground(new java.awt.Color(231, 50, 116));
        btnRecargar1.setText("Recargar Cliente Moral");
        btnRecargar1.setColorNormal(new java.awt.Color(231, 50, 116));
        btnRecargar1.setColorPressed(new java.awt.Color(38, 86, 186));
        btnRecargar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRecargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargar1ActionPerformed(evt);
            }
        });

        comboCrud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Fisica", "Moral" }));
        comboCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCrudActionPerformed(evt);
            }
        });

        btnReporteFisico.setBackground(new java.awt.Color(231, 50, 116));
        btnReporteFisico.setText("Reporte Físico");
        btnReporteFisico.setColorNormal(new java.awt.Color(231, 50, 116));
        btnReporteFisico.setColorPressed(new java.awt.Color(38, 86, 186));
        btnReporteFisico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporteFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteFisicoActionPerformed(evt);
            }
        });

        btnReporteMoral.setBackground(new java.awt.Color(231, 50, 116));
        btnReporteMoral.setText("Reporte Moral");
        btnReporteMoral.setColorNormal(new java.awt.Color(231, 50, 116));
        btnReporteMoral.setColorPressed(new java.awt.Color(38, 86, 186));
        btnReporteMoral.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporteMoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteMoralActionPerformed(evt);
            }
        });

        btnReportePorCompras.setBackground(new java.awt.Color(231, 50, 116));
        btnReportePorCompras.setText("Reporte por compras");
        btnReportePorCompras.setColorNormal(new java.awt.Color(231, 50, 116));
        btnReportePorCompras.setColorPressed(new java.awt.Color(38, 86, 186));
        btnReportePorCompras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReportePorCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportePorComprasActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(231, 50, 116));
        btnAceptar.setText("Aceptar");
        btnAceptar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnAceptar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporteMoral, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReportePorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3)
            .addComponent(jLabel2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtId_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRecargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReporteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReporteMoral, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReportePorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        ClientesCRUDInsertar clientesCRUDInsertar = new ClientesCRUDInsertar(usuario, formularioPadre);
        clientesCRUDInsertar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = jTable1.getSelectedRow();
        String tipo = jTable1.getValueAt(fila, 7).toString();
        
        
        if (txtId_Cliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione un Cliente");
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "¿Confirma la eliminación?", "Eliminar Cliente", JOptionPane.YES_NO_OPTION);
            System.out.println("Opcion: " + confirm);
            if (confirm == 0 && tipo.equals("Moral")) {
                int id_Cliente = Integer.valueOf(txtId_Cliente.getText());
                String message = controllerCliente.eliminarCliente(id_Cliente);
                JOptionPane.showMessageDialog(null, "Cliente eliminado", null, JOptionPane.INFORMATION_MESSAGE);
                controllerCliente.fillTableClienteMoral(jTable1);
            }else if(confirm == 0 && tipo.equals("Fisica")){
                int id_Cliente = Integer.valueOf(txtId_Cliente.getText());
                String message = controllerCliente.eliminarCliente(id_Cliente);
                JOptionPane.showMessageDialog(null, "Cliente eliminado", null, JOptionPane.INFORMATION_MESSAGE);
                controllerCliente.fillTableClienteFisico(jTable1);
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if (txtId_Cliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione un Cliente");
        } else {
            if (comboCrud.getSelectedIndex() == 1 || cambio.getText().equals("1")) {

                int fila = jTable1.getSelectedRow();

                ClientesCRUDIModificar clientesCRUDIModificar = new ClientesCRUDIModificar(usuario, formularioPadre);
                clientesCRUDIModificar.setVisible(true);
                this.setVisible(false);
                ClientesCRUDIModificar.txtRFC.setEnabled(false);
                clientesCRUDIModificar.txtNombreFactura.setEnabled(false);
                int id_cliente = Integer.valueOf(jTable1.getValueAt(fila, 0).toString());
                String nombre = jTable1.getValueAt(fila, 1).toString();
                String paterno = jTable1.getValueAt(fila, 2).toString();
                String materno = jTable1.getValueAt(fila, 3).toString();
                String domicilio = jTable1.getValueAt(fila, 4).toString();
                String telefono = jTable1.getValueAt(fila, 5).toString();
                String correo = jTable1.getValueAt(fila, 6).toString();
                String Tipo = (String) jTable1.getValueAt(fila, 7);

                ClientesCRUDIModificar.txtNumeroCliente.setText(String.valueOf(id_cliente));
                ClientesCRUDIModificar.txtNombre.setText(nombre);
                ClientesCRUDIModificar.jLabel16.setText("Nombre");
                ClientesCRUDIModificar.txtPaterno.setText(paterno);
                ClientesCRUDIModificar.txtMaterno.setText(materno);
                ClientesCRUDIModificar.txtTelefono.setText(telefono);
                ClientesCRUDIModificar.txtDomicilio.setText(domicilio);
                ClientesCRUDIModificar.txtCorreo.setText(correo);
                ClientesCRUDIModificar.tipo_Cliente.setSelectedItem(Tipo);

            } else if (comboCrud.getSelectedIndex() == 2 || cambio.getText().equals("2") || cambio.getText().equals("")) {

                int fila = jTable1.getSelectedRow();

                ClientesCRUDIModificar clientesCRUDIModificar = new ClientesCRUDIModificar(usuario, formularioPadre);
                clientesCRUDIModificar.setVisible(true);
                this.setVisible(false);

                ClientesCRUDIModificar.jLabel16.setText("Razón Social");

                int id_cliente = Integer.valueOf(jTable1.getValueAt(fila, 0).toString());
                String nombre = jTable1.getValueAt(fila, 1).toString();
                String RFC = jTable1.getValueAt(fila, 2).toString();
                String domicilio = jTable1.getValueAt(fila, 3).toString();
                String telefono = jTable1.getValueAt(fila, 4).toString();
                String correo = jTable1.getValueAt(fila, 5).toString();
                String NombreFactura = jTable1.getValueAt(fila, 6).toString();
                String Tipo = (String) jTable1.getValueAt(fila, 7);

                ClientesCRUDIModificar.txtNumeroCliente.setText(String.valueOf(id_cliente));
                ClientesCRUDIModificar.txtNombre.setText(nombre);
                ClientesCRUDIModificar.txtTelefono.setText(telefono);
                ClientesCRUDIModificar.txtDomicilio.setText(domicilio);
                ClientesCRUDIModificar.txtCorreo.setText(correo);
                ClientesCRUDIModificar.txtRFC.setText(RFC);
                ClientesCRUDIModificar.txtNombreFactura.setText(NombreFactura);
                ClientesCRUDIModificar.tipo_Cliente.setSelectedItem(Tipo);
                

            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        String id_cliente = jTable1.getValueAt(fila, 0).toString();
        txtId_Cliente.setText(id_cliente);
        if (formularioPadre.equals("v")) {
            Venta.txtId_Cliente.setText(id_cliente);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        txtId_Cliente.setText("");
        controllerCliente.fillTableClienteFisico(jTable1);
        comboCrud.setSelectedIndex(1);
        cambio.setText("1");
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (formularioPadre.equals("t")) {
            TiendaView tv = new TiendaView(usuario,departamento);
            tv.setVisible(true);
        } else if (formularioPadre.equals("v")) {
            this.setVisible(true);
        } else if (formularioPadre.equals("vi")) {
            this.setVisible(true);
        } else if (formularioPadre.equals("r")) {
            Reportes r = new Reportes(usuario,departamento);
            r.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtId_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_ClienteActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        String busqueda = txtBuscar.getText();
        if (comboCrud.getSelectedIndex() == 1) {
            controllerCliente.buscarTableClienteFisico(jTable1, busqueda);
        } else if (comboCrud.getSelectedIndex() == 2) {
            controllerCliente.buscarTableClienteMoral(jTable1, busqueda);
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnRecargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargar1ActionPerformed
        // TODO add your handling code here:
        txtId_Cliente.setText("");
        controllerCliente.fillTableClienteMoral(jTable1);
        cambio.setText("2");
        comboCrud.setSelectedIndex(2);
    }//GEN-LAST:event_btnRecargar1ActionPerformed

    private void comboCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCrudActionPerformed
        // TODO add your handling code here:
        if (comboCrud.getSelectedIndex() == 1) {
            txtId_Cliente.setText("");
            controllerCliente.fillTableClienteFisico(jTable1);
            cambio.setText("1");
        } else if (comboCrud.getSelectedIndex() == 2) {
            txtId_Cliente.setText("");
            controllerCliente.fillTableClienteMoral(jTable1);
            cambio.setText("2");
        }
    }//GEN-LAST:event_comboCrudActionPerformed

    private void btnReporteFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteFisicoActionPerformed
        ControllerReportes controllerReportes = new ControllerReportes();
        controllerReportes.reporteTipoCliente();
    }//GEN-LAST:event_btnReporteFisicoActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (formularioPadre.equals("v")) {
            int key = evt.getKeyCode();
            if (key == KeyEvent.VK_ENTER) {
                int fila = jTable1.getSelectedRow();
                if (fila < 0) {
                    JOptionPane.showMessageDialog(null, "Seleccione un cliente");
                } else {
                    if (cambio.getText().equals("") || cambio.getText().equals("2")) {
                        String razon_social = jTable1.getValueAt(fila, 1).toString().toUpperCase();
                        Venta.txtNombreCliente.setText(razon_social);
                    } else {
                        String nombre = jTable1.getValueAt(fila, 1).toString().toUpperCase();
                        String apellido_paterno = jTable1.getValueAt(fila, 2).toString().toUpperCase();
                        String apellido_materno = jTable1.getValueAt(fila, 3).toString().toUpperCase();
                        Venta.txtNombreCliente.setText(nombre + " " + apellido_paterno + " " + apellido_materno);
                    }

                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void btnReporteMoralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteMoralActionPerformed
        ControllerReportes controllerReportes = new ControllerReportes();
        controllerReportes.reporteTipoClienteMoral();
    }//GEN-LAST:event_btnReporteMoralActionPerformed

    private void btnReportePorComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportePorComprasActionPerformed
        if (txtId_Cliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        } else {
            ControllerReportes controllerReportes = new ControllerReportes();
            controllerReportes.reporteVentaCliente(Integer.parseInt(txtId_Cliente.getText()));
        }
    }//GEN-LAST:event_btnReportePorComprasActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (formularioPadre.equals("v")) {

            int fila = jTable1.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(null, "Seleccione un cliente");
            } else {
                if (cambio.getText().equals("") || cambio.getText().equals("2")) {
                    String razon_social = jTable1.getValueAt(fila, 1).toString().toUpperCase();
                    Venta.txtNombreCliente.setText(razon_social);
                } else {
                    String nombre = jTable1.getValueAt(fila, 1).toString().toUpperCase();
                    String apellido_paterno = jTable1.getValueAt(fila, 2).toString().toUpperCase();
                    String apellido_materno = jTable1.getValueAt(fila, 3).toString().toUpperCase();
                    Venta.txtNombreCliente.setText(nombre + " " + apellido_paterno + " " + apellido_materno);
                }

                this.setVisible(false);
            }
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnAceptar;
    private com.ortometh.RSbuttom.RSButtonMetro btnEliminar;
    private com.ortometh.RSbuttom.RSButtonMetro btnModificar;
    private com.ortometh.RSbuttom.RSButtonMetro btnNuevo;
    private com.ortometh.RSbuttom.RSButtonMetro btnRecargar;
    private com.ortometh.RSbuttom.RSButtonMetro btnRecargar1;
    public static com.ortometh.RSbuttom.RSButtonMetro btnReporteFisico;
    public static com.ortometh.RSbuttom.RSButtonMetro btnReporteMoral;
    public static com.ortometh.RSbuttom.RSButtonMetro btnReportePorCompras;
    private javax.swing.JTextField cambio;
    private javax.swing.JComboBox<String> comboCrud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtId_Cliente;
    private javax.swing.JTextField txtId_usuario;
    // End of variables declaration//GEN-END:variables
}
