/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.controller.ApartadosController;
import com.ortometh.model.UsuarioLogin;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class ConsultaApartadosView extends javax.swing.JFrame {

    ApartadosController apartadosController = new ApartadosController();

    String apartado;
    int proveedor;
    String cliente;
    String doctor;
    String clinica;
    String costo;
    String fecha;
    String numeroCuarto;
    String abono;
    String resto;
    String observaciones;
    String cambio;
    //variable de usuario
    public static UsuarioLogin usuario;

    /**
     * Creates new form ConsultaApartadosView
     */
    public ConsultaApartadosView() {
        initComponents();
        apartadosController.consultarApartadosProceso(jTable1);
    }

    public ConsultaApartadosView(UsuarioLogin user) {
        initComponents();
        //INICIA DATOS DEL USUARIO
        this.usuario = user;
        this.setLocationRelativeTo(null);
        apartadosController.consultarApartadosProceso(jTable1);
        lblDato.setText("Ingrese la clave del apartado");
        txtFiltroApartado.requestFocus();
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Lista de Apartados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFiltroApartado = new javax.swing.JTextField();
        cbFiltroApartado = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCrear = new com.ortometh.RSbuttom.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();
        lblDato = new javax.swing.JLabel();
        rbProceso = new javax.swing.JRadioButton();
        rbFinalizado = new javax.swing.JRadioButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 599, -1, -1));

        txtFiltroApartado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroApartadoKeyReleased(evt);
            }
        });
        jPanel1.add(txtFiltroApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 230, -1));

        cbFiltroApartado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbFiltroApartado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clave", "Cliente", "Fecha" }));
        cbFiltroApartado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFiltroApartadoItemStateChanged(evt);
            }
        });
        jPanel1.add(cbFiltroApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 160, -1));

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col)
            {
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 1030, 320));

        btnCrear.setBackground(new java.awt.Color(231, 50, 116));
        btnCrear.setText("INICIAR APARTADO");
        btnCrear.setColorNormal(new java.awt.Color(231, 50, 116));
        btnCrear.setColorPressed(new java.awt.Color(38, 86, 186));
        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(67, 98, 158));
        jLabel3.setText("APARTADOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel1.add(lblDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 230, 20));

        buttonGroup1.add(rbProceso);
        rbProceso.setSelected(true);
        rbProceso.setText("En Proceso");
        rbProceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbProcesoMouseClicked(evt);
            }
        });
        rbProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProcesoActionPerformed(evt);
            }
        });
        jPanel1.add(rbProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, -1));

        buttonGroup1.add(rbFinalizado);
        rbFinalizado.setText("Finalizados");
        rbFinalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFinalizadoActionPerformed(evt);
            }
        });
        jPanel1.add(rbFinalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        datos();
        ApartadosView a = new ApartadosView(apartado, 0, usuario);
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        TiendaView atv = new TiendaView(usuario);
        atv.setVisible(true);
        atv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void txtFiltroApartadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroApartadoKeyReleased
        if (rbProceso.isSelected()) {
            if (txtFiltroApartado.getText() != null) {
                apartadosController.consultarApartadosProceso(jTable1, txtFiltroApartado.getText(), String.valueOf(cbFiltroApartado.getSelectedItem()));
            } else {
                apartadosController.consultarApartadosProceso(jTable1);
            }
        } else if (rbFinalizado.isSelected()) {
            if (txtFiltroApartado.getText() != null) {
                apartadosController.consultarApartadosFinalizados(jTable1, txtFiltroApartado.getText(), String.valueOf(cbFiltroApartado.getSelectedItem()));
            } else {
                apartadosController.consultarApartadosFinalizados(jTable1);
            }
        }
    }//GEN-LAST:event_txtFiltroApartadoKeyReleased

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        CrearApartado ca = new CrearApartado(usuario);
        ca.setVisible(true);
        ca.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cbFiltroApartadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFiltroApartadoItemStateChanged
        String item = cbFiltroApartado.getSelectedItem().toString();
        if (item.equalsIgnoreCase("Clave")) {
            lblDato.setText("Ingrese la clave del apartado");
        } else if (item.equalsIgnoreCase("Cliente")) {
            lblDato.setText("Ingrese el nombre del cliente");
        } else if (item.equalsIgnoreCase("Fecha")) {
            lblDato.setText("Ingese la fecha AAAA-MM-DD");
        } else if (item.equalsIgnoreCase("Estado")) {
            lblDato.setText("Ingrese el estado (Proceso/Finalizado)");
        }
        txtFiltroApartado.requestFocus();
    }//GEN-LAST:event_cbFiltroApartadoItemStateChanged

    private void rbProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbProcesoMouseClicked

    }//GEN-LAST:event_rbProcesoMouseClicked

    private void rbProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProcesoActionPerformed
        apartadosController.consultarApartadosProceso(jTable1);
    }//GEN-LAST:event_rbProcesoActionPerformed

    private void rbFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFinalizadoActionPerformed
        apartadosController.consultarApartadosFinalizados(jTable1);
    }//GEN-LAST:event_rbFinalizadoActionPerformed

    private void datos() {
        int rowCount = jTable1.getRowCount();
        int row = jTable1.getSelectedRow();
        int rowc = jTable1.getSelectedRowCount();
        if (rowCount >= 1) {
            if (rowc == 1) {
                apartado = String.valueOf(jTable1.getValueAt(row, 0));
                cliente = String.valueOf(jTable1.getValueAt(row, 1));
                costo = String.valueOf(jTable1.getValueAt(row, 2));
                resto = String.valueOf(jTable1.getValueAt(row, 3));
                fecha = String.valueOf(jTable1.getValueAt(row, 4));
                observaciones = String.valueOf(jTable1.getValueAt(row, 5));
            } else {
                JOptionPane.showMessageDialog(null, "Debe selecionar un solo registro");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaApartadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaApartadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaApartadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaApartadosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaApartadosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbFiltroApartado;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDato;
    private javax.swing.JRadioButton rbFinalizado;
    private javax.swing.JRadioButton rbProceso;
    private javax.swing.JTextField txtFiltroApartado;
    // End of variables declaration//GEN-END:variables
}
