/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.controller.ApartadosController;
import com.ortometh.model.UsuarioLogin;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class CrearApartado extends javax.swing.JFrame {

    ApartadosController controller = new ApartadosController();

    //variable de usuario
    public static UsuarioLogin usuario;
    //Variable de la clave del producto
    public static String clave_producto;
    //Variable del tipo de venta
    public static String tipo_venta = "Tienda";
    //variables 
    String clave;
    int idApartado;
    int cantidad_productos = 0;

    /**
     * Creates new form CrearApartado
     */
    public CrearApartado() {
        initComponents();
        Calendar fecha = Calendar.getInstance();
        lblFecha.setText(fecha.get(Calendar.DATE) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR));
    }

    public CrearApartado(UsuarioLogin user) {
        initComponents();
        this.setLocationRelativeTo(null);
        Calendar fecha = Calendar.getInstance();
        lblFecha.setText(fecha.get(Calendar.DATE) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR));
        //INICIA DATOS DEL USUARIO
        this.usuario = user;
        lblUser.setText(user.getNombreUsuario());
        //INICIA UN APARTADO AL ABRIR LA VENTANA AUTOMATICAMENTE
        controller.crearApartado(usuario.getIdUserLog(), tipo_venta);
        //SELECCIONAR EL ID DEL APARTADO
        clave = controller.claveApartado();
        idApartado = Integer.parseInt(controller.idApartado(clave));
        System.out.println(clave);
        lblFolio.setText(String.valueOf(clave));
        label();
        txtProducto.requestFocus();
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Productos del Apartado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFolio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPiezas = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnCobrar = new com.ortometh.RSbuttom.RSButtonMetro();
        btnProducto = new com.ortometh.RSbuttom.RSButtonMetro();
        btnAgregar = new com.ortometh.RSbuttom.RSButtonMetro();
        btnModificar = new com.ortometh.RSbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col)
            {
                return false;
            }
        };
        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "PRECIO", "MARCA", "CANTIDAD", "DESCUENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProductos);
        if (jtProductos.getColumnModel().getColumnCount() > 0) {
            jtProductos.getColumnModel().getColumn(0).setResizable(false);
            jtProductos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtProductos.getColumnModel().getColumn(1).setResizable(false);
            jtProductos.getColumnModel().getColumn(2).setResizable(false);
            jtProductos.getColumnModel().getColumn(3).setResizable(false);
            jtProductos.getColumnModel().getColumn(4).setResizable(false);
            jtProductos.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1020, 210));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(67, 98, 158));
        jLabel3.setText("FECHA DE APARTADO:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 15, 200, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 98, 158));
        jLabel4.setText("FOLIO:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        lblFolio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(lblFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 15, 160, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(67, 98, 158));
        jLabel5.setText("CODIGO DEL PRODUCTO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtProducto.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtProductoInputMethodTextChanged(evt);
            }
        });
        txtProducto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtProductoPropertyChange(evt);
            }
        });
        txtProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProductoKeyReleased(evt);
            }
        });
        jPanel2.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("DESCUENTO %");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 90, -1));
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(67, 98, 158));
        jLabel7.setText("CANTIDAD");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 60, -1));
        jPanel2.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(67, 98, 158));
        jLabel8.setText("PIEZAS:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(67, 98, 158));
        jLabel9.setText("SUBTOTAL:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(67, 98, 158));
        jLabel11.setText("TOTAL:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, -1, -1));

        lblPiezas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(lblPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 285, 70, 20));

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 70, 20));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 352, 80, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(67, 98, 158));
        jLabel13.setText("APARTADOS");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("USUARIO:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 90, 20));

        btnCobrar.setBackground(new java.awt.Color(231, 50, 116));
        btnCobrar.setText("COBRAR");
        btnCobrar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnCobrar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnCobrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 130, 30));

        btnProducto.setBackground(new java.awt.Color(231, 50, 116));
        btnProducto.setText("BUSCAR PRODUCTO");
        btnProducto.setColorNormal(new java.awt.Color(231, 50, 116));
        btnProducto.setColorPressed(new java.awt.Color(38, 86, 186));
        btnProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 150, 30));

        btnAgregar.setBackground(new java.awt.Color(231, 50, 116));
        btnAgregar.setText("AGREGAR");
        btnAgregar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnAgregar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 110, 30));

        btnModificar.setBackground(new java.awt.Color(231, 50, 116));
        btnModificar.setText("MODIFICAR CANTIDAD");
        btnModificar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnModificar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 150, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1050, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        if (lblTotal.getText().equals("0.00") || lblTotal.getText().equals("0") || lblTotal.getText().equals("0.0")) {
            JOptionPane.showMessageDialog(null, "Debe agregar productos", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            ApartadosView ap = new ApartadosView(clave, 1, usuario);
            ap.setVisible(true);
            ap.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        BuscarProductoView busProductoView = null;
        try {
            busProductoView = new BuscarProductoView(1);
            busProductoView.setVisible(true);
            busProductoView.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            System.out.println("SQL ERROR buscar producto " + ex.getMessage());
        }
    }//GEN-LAST:event_btnProductoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        ConsultaApartadosView ca = new ConsultaApartadosView(usuario);
//        ca.setVisible(true);
//        ca.setLocationRelativeTo(null);
        double total = Double.parseDouble(lblTotal.getText());
        if (total > 0) {
            JOptionPane.showMessageDialog(null, "No puede cancelar el apartado", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ConsultaApartadosView ca = new ConsultaApartadosView(usuario);
            ca.setVisible(true);
            ca.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void txtProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductoKeyReleased
        if (txtProducto.getText().length() == 8) {
            double descuento = 0.0d;
            String producto = controller.idProducto(txtProducto.getText());
            int idProducto = 0;
            if (producto != "") {
                idProducto = Integer.parseInt(producto);
            }
            if (txtProducto.getText().isEmpty() || txtCantidad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe llenar los campos obligatorios", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            } else {
                if (idProducto < 1) {
                    JOptionPane.showMessageDialog(null, "El producto no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
                    limpiar();
                    txtProducto.requestFocus();
                } else {
                    int cantidad = Integer.parseInt(txtCantidad.getText());
                    if (!txtDescuento.getText().isEmpty()) {
                        descuento = Double.parseDouble(txtDescuento.getText());
                    }
                    controller.llenarApartado(idApartado, idProducto, descuento, cantidad, usuario.getIdUserLog());
                    lblPiezas.setText(controller.piezas(idApartado));
                    lblSubtotal.setText(String.valueOf(controller.subtotal(idApartado)));
                    lblTotal.setText(String.valueOf(controller.importe(idApartado)));
                    controller.listProductos(jtProductos, idApartado);
                    limpiar();
                    txtProducto.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txtProductoKeyReleased


    private void txtProductoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtProductoInputMethodTextChanged

    }//GEN-LAST:event_txtProductoInputMethodTextChanged

    private void txtProductoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtProductoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoPropertyChange

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (txtProducto.getText().length() == 8) {
            double descuento = 0.0d;
            String producto = controller.idProducto(txtProducto.getText());
            int idProducto = 0;
            if (producto != "") {
                idProducto = Integer.parseInt(producto);
            }
            if (txtProducto.getText().isEmpty() || txtCantidad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe llenar los campos obligatorios", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            } else {
                if (idProducto < 1) {
                    JOptionPane.showMessageDialog(null, "El producto no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
                    limpiar();
                    txtProducto.requestFocus();
                } else {
                    int cantidad = Integer.parseInt(txtCantidad.getText());
                    if (!txtDescuento.getText().isEmpty()) {
                        descuento = Double.parseDouble(txtDescuento.getText());
                    }
                    controller.llenarApartado(idApartado, idProducto, descuento, cantidad, usuario.getIdUserLog());
                    lblPiezas.setText(controller.piezas(idApartado));
                    lblSubtotal.setText(String.valueOf(controller.subtotal(idApartado)));
                    lblTotal.setText(String.valueOf(controller.importe(idApartado)));
                    controller.listProductos(jtProductos, idApartado);
                    limpiar();
                    txtProducto.requestFocus();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese la clave completa", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jtProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductosMouseClicked
        int row = jtProductos.getSelectedRow();
        String codigo_producto = String.valueOf(jtProductos.getValueAt(row, 0));
        txtProducto.setText(codigo_producto);
    }//GEN-LAST:event_jtProductosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String codigo_producto = txtProducto.getText();
        if (codigo_producto.isEmpty() || txtCantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese la clave del producto y la cantidad nueva");
        } else {
            int cantidad = Integer.parseInt(txtCantidad.getText());
            int idProducto = Integer.parseInt(controller.idProducto(codigo_producto));
            controller.cambiarCantidad(idApartado, idProducto, cantidad);
            controller.listProductos(jtProductos, idApartado);
            lblPiezas.setText(controller.piezas(idApartado));
            lblSubtotal.setText(String.valueOf(controller.subtotal(idApartado)));
            lblTotal.setText(String.valueOf(controller.importe(idApartado)));
            limpiar();
            txtProducto.requestFocus();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void limpiar() {
        txtCantidad.setText("1");
        txtProducto.setText("");
        txtDescuento.setText("0");
    }

    private void label() {
        txtCantidad.setText("1");
        lblPiezas.setText("0");
        lblSubtotal.setText("0.0");
        lblTotal.setText("0.0");
        txtDescuento.setText("0");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearApartado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearApartado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearApartado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearApartado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearApartado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnAgregar;
    private com.ortometh.RSbuttom.RSButtonMetro btnCobrar;
    private com.ortometh.RSbuttom.RSButtonMetro btnModificar;
    private com.ortometh.RSbuttom.RSButtonMetro btnProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtProductos;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblPiezas;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescuento;
    public static javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
