/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.model.UsuarioLogin;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Alexis
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form TiendaView
     */
    public static MenuView frmMenuView;
    public static UsuarioLogin usuario;

    public MenuView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public MenuView(UsuarioLogin user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = user;
        System.out.println("Id Usuario Login " + user.getIdUserLog());
//        int idUserLogin= user.getIdUserLog();
        lblMenu.requestFocus();
        txtIdUsuarioLogin.setText(String.valueOf(user.getIdUserLog()));
        txtNombreLogin.setText(String.valueOf(user.getNombreUsuario()));
        txtIdUsuarioLogin.setVisible(false);
        txtNombreLogin.setVisible(false);
        
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Menú Ortometh");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        rSButtonMetro1 = new com.ortometh.RSbuttom.RSButtonMetro();
        jLabel6 = new javax.swing.JLabel();
        txtIdUsuarioLogin = new javax.swing.JTextField();
        btnUusarios = new com.ortometh.RSbuttom.RSButtonMetro();
        txtNombreLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        lblMenu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(67, 98, 158));
        lblMenu.setText("MENÚ");
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 237, -1, -1));

        rSButtonMetro1.setText("TIENDA");
        rSButtonMetro1.setColorNormal(new java.awt.Color(144, 67, 96));
        rSButtonMetro1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 197, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("CERRAR SESIÓN");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 202, -1, -1));
        getContentPane().add(txtIdUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 40, -1));

        btnUusarios.setBackground(new java.awt.Color(67, 98, 158));
        btnUusarios.setText("USUARIOS");
        btnUusarios.setColorNormal(new java.awt.Color(67, 98, 158));
        btnUusarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUusarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUusariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUusarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 200, 80));
        getContentPane().add(txtNombreLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        TiendaView a = new TiendaView(usuario);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void btnUusariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUusariosActionPerformed
        // TODO add your handling code here:
        UsuariosView us = new UsuariosView(usuario);
        us.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUusariosActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnUusarios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblMenu;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro1;
    public static javax.swing.JTextField txtIdUsuarioLogin;
    private javax.swing.JTextField txtNombreLogin;
    // End of variables declaration//GEN-END:variables
}
