/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.controller.ProductoController;
import com.ortometh.model.UsuarioLogin;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jacQu
 */
public class ProductosCRUD extends javax.swing.JFrame {

    ProductoController productoController = new ProductoController();
    public static UsuarioLogin usuario;

    public ProductosCRUD(UsuarioLogin user) throws SQLException {
        initComponents();
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Productos"); 
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        this.usuario = user;
        System.out.println("Id Usuario Login " + user.getIdUserLog());
        txtId_usuario.setText(String.valueOf(usuario.getIdUserLog()));
        //Mostrar datos de la tabla
        productoController.fillProductoInventario(jTable1);
        // Ocultar txtField
        txtId_producto.setText("");
        txtId_usuario.setVisible(false);
        txtId_producto.setVisible(false);
        comboFiltro2.setSelectedItem(null);
        ComboFiltro.setSelectedIndex(0);
       
        
    }

    private ProductosCRUD() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnNuevo = new com.ortometh.RSbuttom.RSButtonMetro();
        btnEliminar = new com.ortometh.RSbuttom.RSButtonMetro();
        btnGuardar = new com.ortometh.RSbuttom.RSButtonMetro();
        ComboFiltro = new javax.swing.JComboBox<>();
        btnBuscar = new com.ortometh.RSbuttom.RSButtonMetro();
        btnRecargar = new com.ortometh.RSbuttom.RSButtonMetro();
        txtId_producto = new javax.swing.JTextField();
        comboFiltro2 = new javax.swing.JComboBox<>();
        txtId_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar1 = new com.ortometh.RSbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(1054, 706));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 283, 1030, 270));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("Productos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(231, 50, 116));
        btnNuevo.setText("Nuevo");
        btnNuevo.setColorNormal(new java.awt.Color(231, 50, 116));
        btnNuevo.setColorPressed(new java.awt.Color(38, 86, 186));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, 90, 20));

        btnEliminar.setBackground(new java.awt.Color(231, 50, 116));
        btnEliminar.setText("Eliminar");
        btnEliminar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnEliminar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 90, 20));

        btnGuardar.setBackground(new java.awt.Color(231, 50, 116));
        btnGuardar.setText("Modificar");
        btnGuardar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnGuardar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 90, 20));

        ComboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtro", "Categoria", "Tipo", "Proveedor" }));
        ComboFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboFiltroItemStateChanged(evt);
            }
        });
        getContentPane().add(ComboFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, -1));

        btnBuscar.setBackground(new java.awt.Color(231, 50, 116));
        btnBuscar.setText("Buscar");
        btnBuscar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnBuscar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 70, 20));

        btnRecargar.setBackground(new java.awt.Color(231, 50, 116));
        btnRecargar.setText("Recargar");
        btnRecargar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnRecargar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnRecargar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 70, 20));

        txtId_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_productoActionPerformed(evt);
            }
        });
        getContentPane().add(txtId_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 565, 56, -1));

        getContentPane().add(comboFiltro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 191, -1));
        getContentPane().add(txtId_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 565, 56, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBuscar1.setBackground(new java.awt.Color(231, 50, 116));
        btnBuscar1.setText("Categorias");
        btnBuscar1.setColorNormal(new java.awt.Color(231, 50, 116));
        btnBuscar1.setColorPressed(new java.awt.Color(38, 86, 186));
        btnBuscar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        ProductosCRUDInsertar cRUDInsertar = new ProductosCRUDInsertar(usuario);
        cRUDInsertar.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            if (txtId_producto.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Seleccione un producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                int confirm = JOptionPane.showConfirmDialog(null, "¿Confirma la eliminación?", "Eliminar producto", JOptionPane.YES_NO_OPTION);
                System.out.println("Opcion: " + confirm);
                if (confirm == 0) {
                    String clave_producto = txtId_producto.getText();
                    if (productoController.eliminarProducto(clave_producto) == true) {
                        JOptionPane.showMessageDialog(null, "Producto eliminado", null, JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se a podido eliminar", null, JOptionPane.INFORMATION_MESSAGE);
                    }
                    try {
                        productoController.refillProducto(jTable1);
                    } catch (SQLException ex) {
                        Logger.getLogger(ProductosCRUD.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
             JOptionPane.showMessageDialog(null, "Seleccione un producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {

            if (txtId_producto.getText().equals("")) {
                 JOptionPane.showMessageDialog(null, "Seleccione un producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                ProductosCRUDIModificar productosCRUDIModificar = new ProductosCRUDIModificar(usuario);
                productosCRUDIModificar.setVisible(true);
                this.setVisible(false);
                //Obtener valores de la tabla
                String tipo_producto = jTable1.getValueAt(fila, 2).toString();
                String clave = jTable1.getValueAt(fila, 4).toString();
                String marca = jTable1.getValueAt(fila, 5).toString();
                String categoria = jTable1.getValueAt(fila, 1).toString();
                String proveedor = jTable1.getValueAt(fila, 3).toString();
                String descripcion = jTable1.getValueAt(fila, 6).toString();
                String stock = jTable1.getValueAt(fila, 7).toString();
                String stock_min = jTable1.getValueAt(fila, 8).toString();
                String precio_venta = jTable1.getValueAt(fila, 9).toString();
                String precio_compra = jTable1.getValueAt(fila, 10).toString();
                //Mandar valores a la vista de modificar
                ProductosCRUDIModificar.tipo_producto.setSelectedItem(tipo_producto);
                ProductosCRUDIModificar.txtclave.setText(String.valueOf(clave));
                ProductosCRUDIModificar.txtmarca.setText(marca);
                ProductosCRUDIModificar.categoria.setSelectedItem(categoria);
                ProductosCRUDIModificar.proveedor.setSelectedItem(proveedor);
                ProductosCRUDIModificar.txtdescripcion.setText(descripcion);
                ProductosCRUDIModificar.txtstock.setText(String.valueOf(stock));
                ProductosCRUDIModificar.txtstock_min.setText(String.valueOf(stock_min));
                ProductosCRUDIModificar.txtPrecio_venta.setText(String.valueOf(precio_venta));
                ProductosCRUDIModificar.txtPrecio_compra.setText(String.valueOf(precio_compra));
                ProductosCRUDIModificar.txtid_producto.setText(txtId_producto.getText());
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        String clave_producto = jTable1.getValueAt(fila, 0).toString();
        txtId_producto.setText(clave_producto);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (ComboFiltro.getSelectedIndex() == 0 || comboFiltro2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un filtro de busqueda", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            if (ComboFiltro.getSelectedIndex() == 3) {
                String prov = comboFiltro2.getSelectedItem().toString();
                int id_proveedor = 0;
                try {
                    id_proveedor = productoController.id_proveedor(prov);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductosCRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    productoController.filtrarProductoProveedor(jTable1, id_proveedor);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductosCRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //categoria
            if (ComboFiltro.getSelectedIndex() == 1) {
                String categoria = comboFiltro2.getSelectedItem().toString();
                int id_categoria = 0;
                try {
                    id_categoria = productoController.id_categoria(categoria);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductosCRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    productoController.filtrarProductoCategoria(jTable1, id_categoria);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductosCRUD.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            //tipo
            if (ComboFiltro.getSelectedIndex() == 2) {
                String tipo = comboFiltro2.getSelectedItem().toString();
                int id_tipo = 0;
                try {
                    id_tipo = productoController.Id_tipo(tipo);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductosCRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    productoController.filtrarProductoTipo(jTable1, id_tipo);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductosCRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        txtId_producto.setText("");
        try {
            productoController.refillProducto(jTable1);
            if (comboFiltro2.getSelectedIndex() != 0 && ComboFiltro.getSelectedIndex() != 0) {
                comboFiltro2.setSelectedIndex(0);
                ComboFiltro.setSelectedIndex(0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductosCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void ComboFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboFiltroItemStateChanged
        //categoria
        if (ComboFiltro.getSelectedIndex() == 0) {
            comboFiltro2.removeAllItems();
        }
        //categoria
        if (ComboFiltro.getSelectedIndex() == 1) {
            productoController.fillComboCategoria(comboFiltro2);
        }
        //tipo
        if (ComboFiltro.getSelectedIndex() == 2) {
            productoController.fillCombotTipo_producto(comboFiltro2);
        }
        //proveedor
        if (ComboFiltro.getSelectedIndex() == 3) {
            productoController.fillComboProveedor(comboFiltro2);
        }
    }//GEN-LAST:event_ComboFiltroItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        TiendaView tv = new TiendaView(usuario);
        tv.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void txtId_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_productoActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        CategoriasInsertar categoriasInsertar = new CategoriasInsertar(usuario);
        categoriasInsertar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboFiltro;
    private com.ortometh.RSbuttom.RSButtonMetro btnBuscar;
    private com.ortometh.RSbuttom.RSButtonMetro btnBuscar1;
    private com.ortometh.RSbuttom.RSButtonMetro btnEliminar;
    private com.ortometh.RSbuttom.RSButtonMetro btnGuardar;
    private com.ortometh.RSbuttom.RSButtonMetro btnNuevo;
    private com.ortometh.RSbuttom.RSButtonMetro btnRecargar;
    private javax.swing.JComboBox<String> comboFiltro2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtId_producto;
    private javax.swing.JTextField txtId_usuario;
    // End of variables declaration//GEN-END:variables
}
