/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.controller.ProductoController;
import com.ortometh.model.Departamento;
import com.ortometh.model.Events;
import com.ortometh.model.UsuarioLogin;
import static com.ortometh.viewMain.ProductosCRUDIModificar.usuario;
import java.awt.Color;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jacQu
 */
public class ProductosCRUDInsertar extends javax.swing.JFrame {
    ProductoController productoController = new ProductoController();
    Events evento = new Events();
    public static UsuarioLogin usuario;
     public static Departamento departamento;
    /**
     * Creates new form ProductosCRUD
     */
    public ProductosCRUDInsertar(UsuarioLogin user,Departamento dep) {
        initComponents();
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Insertar Producto"); 
        this.departamento = dep;
        System.out.println("ID:" + departamento.getIdDepartamento() + " Nombre:" + departamento.getNombre());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        productoController.fillCombotTipo_producto(tipo_producto);
        productoController.fillComboCategoria(categoria);
        productoController.fillComboProveedor(proveedor);
        this.usuario = user;
        System.out.println("Id Usuario Login " + user.getIdUserLog());
        txtid_usuario.setText(String.valueOf(usuario.getIdUserLog()));
        txtid_usuario.setVisible(false);
  
    }

    private ProductosCRUDInsertar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        rSButtonMetro1 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro5 = new com.ortometh.RSbuttom.RSButtonMetro();
        txtPrecio_compra = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        txtstock = new javax.swing.JTextField();
        txtstock_min = new javax.swing.JTextField();
        txtPrecio_venta = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        proveedor = new javax.swing.JComboBox<>();
        categoria = new javax.swing.JComboBox<>();
        tipo_producto = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtid_usuario = new javax.swing.JTextField();
        txtclave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("Insertar");

        rSButtonMetro1.setBackground(new java.awt.Color(231, 50, 116));
        rSButtonMetro1.setText("CANCELAR");
        rSButtonMetro1.setColorNormal(new java.awt.Color(231, 50, 116));
        rSButtonMetro1.setColorPressed(new java.awt.Color(38, 86, 186));
        rSButtonMetro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        rSButtonMetro5.setBackground(new java.awt.Color(231, 50, 116));
        rSButtonMetro5.setText("GUARDAR");
        rSButtonMetro5.setColorNormal(new java.awt.Color(231, 50, 116));
        rSButtonMetro5.setColorPressed(new java.awt.Color(38, 86, 186));
        rSButtonMetro5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });

        txtPrecio_compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecio_compraKeyTyped(evt);
            }
        });

        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyTyped(evt);
            }
        });

        txtstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstockKeyTyped(evt);
            }
        });

        txtstock_min.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstock_minKeyTyped(evt);
            }
        });

        txtPrecio_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecio_ventaKeyTyped(evt);
            }
        });

        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmarcaKeyTyped(evt);
            }
        });

        proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tipo_producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setForeground(new java.awt.Color(67, 98, 158));
        jLabel14.setText("Tipo");

        jLabel15.setForeground(new java.awt.Color(67, 98, 158));
        jLabel15.setText("Clave");

        jLabel16.setForeground(new java.awt.Color(67, 98, 158));
        jLabel16.setText("Marca");

        jLabel17.setForeground(new java.awt.Color(67, 98, 158));
        jLabel17.setText("Categoría");

        jLabel18.setForeground(new java.awt.Color(67, 98, 158));
        jLabel18.setText("Stock Mínimo");

        jLabel19.setForeground(new java.awt.Color(67, 98, 158));
        jLabel19.setText("Proveedor");

        jLabel20.setForeground(new java.awt.Color(67, 98, 158));
        jLabel20.setText("Descripción");

        jLabel21.setForeground(new java.awt.Color(67, 98, 158));
        jLabel21.setText("Stock Actual");

        jLabel22.setForeground(new java.awt.Color(67, 98, 158));
        jLabel22.setText("Precio para venta");

        jLabel23.setForeground(new java.awt.Color(67, 98, 158));
        jLabel23.setText("Precio de compra");

        txtclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclaveKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtstock))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(txtid_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtclave))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtmarca))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtdescripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proveedor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecio_compra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecio_venta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tipo_producto, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtstock_min)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(175, 175, 175))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(5, 5, 5)
                .addComponent(tipo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(3, 3, 3)
                .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtstock_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecio_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(rSButtonMetro5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtid_usuario, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        ProductosCRUD productosCRUD = null;
        try {
            productosCRUD = new ProductosCRUD(usuario,departamento);
        } catch (SQLException ex) {
            Logger.getLogger(ProductosCRUDInsertar.class.getName()).log(Level.SEVERE, null, ex);
        }
        productosCRUD.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed

         if (txtclave.getText().equals("") || txtmarca.getText().equals("") ||
                 txtdescripcion.getText().equals("") || txtstock.getText().equals("")|| 
                 txtstock_min.getText().equals("")|| txtPrecio_venta.getText().equals("")||
                 txtPrecio_compra.getText().equals("") || tipo_producto.getSelectedIndex() == 0
                 || categoria.getSelectedIndex()==0 || proveedor.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios", "Advertencia", JOptionPane.WARNING_MESSAGE);
          } 
         else{
          String tipo = tipo_producto.getSelectedItem().toString();
          int id_tipo=0;
             try {
                 id_tipo = productoController.Id_tipo(tipo);
             } catch (SQLException ex) {
                 Logger.getLogger(ProductosCRUDInsertar.class.getName()).log(Level.SEVERE, null, ex);
             }
          int clave = Integer.parseInt(txtclave.getText());
          String marca = txtmarca.getText();
          String cate = categoria.getSelectedItem().toString();
          int id_categoria=0;
             try {
                 id_categoria = productoController.id_categoria(cate);
             } catch (SQLException ex) {
                 Logger.getLogger(ProductosCRUDInsertar.class.getName()).log(Level.SEVERE, null, ex);
             }
          String prov = this.proveedor.getSelectedItem().toString();
          int id_proveedor=0;
             try {
                 id_proveedor = productoController.id_proveedor(prov);
             } catch (SQLException ex) {
                 Logger.getLogger(ProductosCRUDInsertar.class.getName()).log(Level.SEVERE, null, ex);
             }
          String descripcion= txtdescripcion.getText();
          int stock = Integer.parseInt(txtstock.getText());
          int stock_min = Integer.parseInt(txtstock_min.getText());
          double precio_venta = Double.parseDouble(txtPrecio_venta.getText());
          double precio_compra = Double.parseDouble(txtPrecio_compra.getText());
          
          if(!productoController.insertar_producto(id_categoria, id_tipo, id_proveedor, clave, marca, descripcion, stock, stock_min, precio_venta, precio_compra, usuario.getIdUserLog())== true){
              JOptionPane.showMessageDialog(null, "El producto se a registrado correctamente", null, JOptionPane.INFORMATION_MESSAGE);
             limpiar();
          }else{
               JOptionPane.showMessageDialog(null, "Error el producto no se a podido registrar ", null, JOptionPane.INFORMATION_MESSAGE);
          }
         }
        
         
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed
    public void limpiar(){
        txtPrecio_compra.setText("");
        txtPrecio_venta.setText("");
        txtclave.setText("");
        txtdescripcion.setText("");
        txtmarca.setText("");
        txtstock.setText("");
        txtstock_min.setText("");
        tipo_producto.setSelectedIndex(0);
        categoria.setSelectedIndex(0);
        proveedor.setSelectedIndex(0);
        
    }
    private void txtstockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstockKeyTyped
        evento.numberKeyPress(evt);
        evento.limitCharacters(evt, txtclave,10);
    }//GEN-LAST:event_txtstockKeyTyped

    private void txtstock_minKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstock_minKeyTyped
        evento.numberKeyPress(evt);
        evento.limitCharacters(evt, txtclave,10);
    }//GEN-LAST:event_txtstock_minKeyTyped

    private void txtmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyTyped
        evento.upperFisrtLetter(evt, txtmarca);
        evento.textVarcharKeyPress(evt);

        
    }//GEN-LAST:event_txtmarcaKeyTyped

    private void txtdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyTyped
        evento.upperFisrtLetter(evt, txtdescripcion);
    }//GEN-LAST:event_txtdescripcionKeyTyped

    private void txtclaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclaveKeyTyped
        evento.numberKeyPress(evt);
    }//GEN-LAST:event_txtclaveKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ProductosCRUD cRUD = null;
        try {
            cRUD = new ProductosCRUD(usuario,departamento);
        } catch (SQLException ex) {
            Logger.getLogger(ProductosCRUDInsertar.class.getName()).log(Level.SEVERE, null, ex);
        }
        cRUD.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void txtPrecio_ventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecio_ventaKeyTyped
        evento.numberDecimalKeyPress(evt, txtPrecio_venta);
    }//GEN-LAST:event_txtPrecio_ventaKeyTyped

    private void txtPrecio_compraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecio_compraKeyTyped
        evento.numberDecimalKeyPress(evt, txtPrecio_compra);
    }//GEN-LAST:event_txtPrecio_compraKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosCRUDInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosCRUDInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosCRUDInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosCRUDInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosCRUDInsertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> proveedor;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro1;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro5;
    private javax.swing.JComboBox<String> tipo_producto;
    private javax.swing.JTextField txtPrecio_compra;
    private javax.swing.JTextField txtPrecio_venta;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtid_usuario;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txtstock_min;
    // End of variables declaration//GEN-END:variables
}
