/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.controller.ProveedorController;
import com.ortometh.model.Events;
import com.ortometh.model.UsuarioLogin;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexis
 */
public class ProveedoresView extends javax.swing.JFrame {

    /**
     * Creates new form TiendaView
     */
    ProveedorController proveedorController = new ProveedorController();
    Events evento = new Events();
    public static UsuarioLogin usuarioLog;

    public ProveedoresView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        proveedorController.fillProveedores(tableProveedores);
        txtusuarioID.setText(String.valueOf(1));
        txtproveedorID.setVisible(false);
        txtActions.setVisible(false);
        txtActions.setText("i");
        txtusuarioID.setVisible(false);
        btnEliminar.setVisible(false);
        btnNuevo.setVisible(false);
        txtNombre.requestFocus();
    }

    public ProveedoresView(UsuarioLogin user) {
        initComponents();
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Proveedores"); 
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.usuarioLog = user;
        proveedorController.fillProveedores(tableProveedores);
        txtusuarioID.setText(String.valueOf(user.getIdUserLog()));
        txtproveedorID.setVisible(false);
        txtActions.setVisible(false);
        txtusuarioID.setVisible(false);
        txtActions.setText("i");
        btnEliminar.setVisible(false);
        btnNuevo.setVisible(false);
        txtNombre.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProveedores = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEliminar = new com.ortometh.RSbuttom.RSButtonMetro();
        btnNuevo = new com.ortometh.RSbuttom.RSButtonMetro();
        btnGuardar = new com.ortometh.RSbuttom.RSButtonMetro();
        txtTelefono = new javax.swing.JTextField();
        txtFiltrar = new javax.swing.JTextField();
        txtRFC = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtproveedorID = new javax.swing.JTextField();
        txtusuarioID = new javax.swing.JTextField();
        txtActions = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cbxBusqueda = new javax.swing.JComboBox<>();
        btnBuscar = new com.ortometh.RSbuttom.RSButtonMetro();
        btnRecargar = new com.ortometh.RSbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        jLabel1.setForeground(new java.awt.Color(67, 98, 158));
        jLabel1.setText("Correo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        tableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "RFC", "TELEFONO", "CORREO"
            }
        ));
        tableProveedores.getTableHeader().setReorderingAllowed(false);
        tableProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProveedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 710, 300));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 98, 158));
        jLabel4.setText("Proveedores");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        jLabel5.setForeground(new java.awt.Color(67, 98, 158));
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("RFC");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel7.setForeground(new java.awt.Color(67, 98, 158));
        jLabel7.setText("Teléfono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(231, 50, 116));
        btnEliminar.setText("Eliminar");
        btnEliminar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnEliminar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 90, 30));

        btnNuevo.setBackground(new java.awt.Color(231, 50, 116));
        btnNuevo.setText("Nuevo");
        btnNuevo.setColorNormal(new java.awt.Color(231, 50, 116));
        btnNuevo.setColorPressed(new java.awt.Color(38, 86, 186));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 90, 30));

        btnGuardar.setBackground(new java.awt.Color(231, 50, 116));
        btnGuardar.setText("Guardar");
        btnGuardar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnGuardar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 80, 30));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 280, -1));
        txtTelefono.getAccessibleContext().setAccessibleName("");
        txtTelefono.getAccessibleContext().setAccessibleDescription("");

        txtFiltrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltrarKeyReleased(evt);
            }
        });
        getContentPane().add(txtFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 400, -1));

        txtRFC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCKeyTyped(evt);
            }
        });
        getContentPane().add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, -1));

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 280, -1));

        txtproveedorID.setEditable(false);
        txtproveedorID.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtproveedorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 90, -1));

        txtusuarioID.setEditable(false);
        txtusuarioID.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtusuarioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 90, -1));
        getContentPane().add(txtActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(989, 560, 40, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, -1));

        cbxBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "RFC" }));
        getContentPane().add(cbxBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 120, -1));

        btnBuscar.setBackground(new java.awt.Color(231, 50, 116));
        btnBuscar.setText("Buscar");
        btnBuscar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnBuscar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 70, 20));

        btnRecargar.setBackground(new java.awt.Color(231, 50, 116));
        btnRecargar.setText("Recargar");
        btnRecargar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnRecargar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnRecargar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //Eliminar Proveedor
        int confirm = JOptionPane.showConfirmDialog(null, "¿Confirma la eliminación?", "Eliminar proveedor", JOptionPane.YES_NO_OPTION);
        System.out.println("Opcion: " + confirm);
        if (confirm == 0) {
            int proveedorID = Integer.parseInt(txtproveedorID.getText());
            String message = proveedorController.eliminarProveedor(proveedorID);
            recargarTabla();
            JOptionPane.showMessageDialog(null, message, "Eliminar Proveedor", JOptionPane.INFORMATION_MESSAGE);
            clearTextFileds();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // Boton Nuevo
        txtActions.setText("i");
        clearTextFileds();
        btnEliminar.setVisible(false);
        btnNuevo.setVisible(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Botton Guardar
        if (txtActions.getText().equals("i")) {
            if (txtNombre.getText().equals("") || txtRFC.getText().equals("") || txtTelefono.getText().equals("") || txtCorreo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Llene todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                String nombre = txtNombre.getText();
                String RFC = txtRFC.getText();
                String telefono = txtTelefono.getText();
                String correo = txtCorreo.getText();
                int usuarioID = Integer.parseInt(txtusuarioID.getText());

                if (evento.validarEmail(correo)) {
                    String message = proveedorController.ingresarProveedor(nombre, RFC, telefono, correo, usuarioID);
                    recargarTabla();
                    clearTextFileds();
                    btnEliminar.setVisible(false);
                    JOptionPane.showMessageDialog(null, message, "Registro de Proveedor", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Correo no válido", "Advertencia", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else if (txtActions.getText().equals("m")) {
            if (txtNombre.getText().equals("") || txtRFC.getText().equals("") || txtTelefono.getText().equals("") || txtCorreo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campos vacíos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                int idProveedor = Integer.parseInt(txtproveedorID.getText());
                String nombre = txtNombre.getText();
                String RFC = txtRFC.getText();
                String telefono = txtTelefono.getText();
                String correo = txtCorreo.getText();
                int usuarioID = Integer.parseInt(txtusuarioID.getText());

                if (evento.validarEmail(correo)) {
                    String message = proveedorController.modificarProveedor(idProveedor, nombre, RFC, telefono, correo, usuarioID);
                    recargarTabla();
                    clearTextFileds();
                    btnEliminar.setVisible(false);
                    JOptionPane.showMessageDialog(null, message, "Actualización de Proveedor", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Correo no válido");
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tableProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProveedoresMouseClicked
        // TODO add your handling code here:
        btnEliminar.setVisible(true);
        btnNuevo.setVisible(true);

        int fila = tableProveedores.getSelectedRow();

        int id = (int) tableProveedores.getValueAt(fila, 0);
        String nombre = tableProveedores.getValueAt(fila, 1).toString();
        String RFC = tableProveedores.getValueAt(fila, 2).toString();
        String telefono = tableProveedores.getValueAt(fila, 3).toString();
        String correo = tableProveedores.getValueAt(fila, 4).toString();

        txtproveedorID.setText(String.valueOf(id));
        txtNombre.setText(nombre);
        txtRFC.setText(RFC);
        txtTelefono.setText(telefono);
        txtCorreo.setText(correo);
        txtActions.setText("m");
    }//GEN-LAST:event_tableProveedoresMouseClicked

    private void txtRFCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyReleased
        // TODO add your handling code here:
        evento.toUpperCase(txtRFC);
    }//GEN-LAST:event_txtRFCKeyReleased

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        evento.numberKeyPress(evt);
        evento.limitCharacters(evt, txtTelefono, 15);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCKeyTyped
        // TODO add your handling code here:
        evento.limitCharacters(evt, txtRFC, 13);
        evento.textVarcharKeyPress(evt);
    }//GEN-LAST:event_txtRFCKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        evento.upperFisrtLetter(evt, txtNombre);
        evento.textVarcharKeyPress(evt);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (!txtFiltrar.getText().equals("")) {
            String parametro = txtFiltrar.getText();
            if (cbxBusqueda.getSelectedIndex() == 0) {
                if (!proveedorController.getProveedorByNombre(tableProveedores, parametro)) {
                    recargarTabla();
                    JOptionPane.showMessageDialog(null, "Verifique los datos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
                txtFiltrar.setText(null);
            } else if (cbxBusqueda.getSelectedIndex() == 1) {
                if (!proveedorController.getProveedorByRFC(tableProveedores, parametro)) {
                    recargarTabla();
                    JOptionPane.showMessageDialog(null, "Verifique los datos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
                txtFiltrar.setText(null);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Campo vacío", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
        recargarTabla();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void txtFiltrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarKeyReleased
        // TODO add your handling code here:
        if (cbxBusqueda.getSelectedIndex() == 0) {
            evento.upperFisrtLetter(evt, txtFiltrar);
        } else if (cbxBusqueda.getSelectedIndex() == 1) {
            evento.toUpperCase(txtFiltrar);
        }
    }//GEN-LAST:event_txtFiltrarKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        TiendaView tv = new TiendaView(usuarioLog);
        tv.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void clearTextFileds() {
        txtNombre.setText(null);
        txtRFC.setText(null);
        txtTelefono.setText(null);
        txtCorreo.setText(null);
        txtproveedorID.setText(null);
    }
    
    private void recargarTabla(){
        proveedorController.reFillProveedores(tableProveedores);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedoresView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProveedoresView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnBuscar;
    private com.ortometh.RSbuttom.RSButtonMetro btnEliminar;
    private com.ortometh.RSbuttom.RSButtonMetro btnGuardar;
    private com.ortometh.RSbuttom.RSButtonMetro btnNuevo;
    private com.ortometh.RSbuttom.RSButtonMetro btnRecargar;
    private javax.swing.JComboBox<String> cbxBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProveedores;
    private javax.swing.JTextField txtActions;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFiltrar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtproveedorID;
    private javax.swing.JTextField txtusuarioID;
    // End of variables declaration//GEN-END:variables
}
