/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.controller.ApartadosController;
import com.ortometh.controller.ControllerReportes;
import com.ortometh.controller.ProductoController;
import com.ortometh.controller.ProveedorController;
import com.ortometh.model.UsuarioLogin;
import java.awt.Image;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jacQu
 */
public class ReportesProductos extends javax.swing.JFrame {

    ControllerReportes controllerReportes = new ControllerReportes();
    ApartadosController controllerApartados = new ApartadosController();
    ProductoController controllerProducto = new ProductoController();
    ProveedorController proveedorController = new ProveedorController();
    public static UsuarioLogin usuario;

    /**
     * Creates new form Reportes
     */
    public ReportesProductos(UsuarioLogin user) {
        initComponents();
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Reportes Productos"); 
        
        buttonGroup1.add(jRadioCategoria);
        buttonGroup1.add(jRadioProveedor);
        buttonGroup1.add(jRadioStockMax);
        buttonGroup1.add(jRadioStockMin);
        buttonGroup1.add(jRadioTipo);
        buttonGroup1.add(jRadioReporteGeneral);

        setLocationRelativeTo(null);
        this.setResizable(false);
        this.usuario = user;
        
        jRadioCategoria.setSelected(true);
        controllerProducto.fillComboCategoria(jComboBox1);
        jComboBox1.setEnabled(true);
    }

    ReportesProductos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioCategoria = new javax.swing.JRadioButton();
        jRadioProveedor = new javax.swing.JRadioButton();
        jRadioTipo = new javax.swing.JRadioButton();
        jRadioStockMin = new javax.swing.JRadioButton();
        jRadioStockMax = new javax.swing.JRadioButton();
        jRadioReporteGeneral = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jRadioCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jRadioCategoria.setText("Categoria");
        jRadioCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioCategoriaMouseClicked(evt);
            }
        });
        jRadioCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCategoriaActionPerformed(evt);
            }
        });

        jRadioProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jRadioProveedor.setText("Proveedor");
        jRadioProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioProveedorMouseClicked(evt);
            }
        });
        jRadioProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioProveedorActionPerformed(evt);
            }
        });

        jRadioTipo.setBackground(new java.awt.Color(255, 255, 255));
        jRadioTipo.setText("Tipo Producto");
        jRadioTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioTipoMouseClicked(evt);
            }
        });

        jRadioStockMin.setBackground(new java.awt.Color(255, 255, 255));
        jRadioStockMin.setText("Stock Min");
        jRadioStockMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioStockMinMouseClicked(evt);
            }
        });

        jRadioStockMax.setBackground(new java.awt.Color(255, 255, 255));
        jRadioStockMax.setText("Stock Max");
        jRadioStockMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioStockMaxMouseClicked(evt);
            }
        });

        jRadioReporteGeneral.setBackground(new java.awt.Color(255, 255, 255));
        jRadioReporteGeneral.setText("Reporte General");
        jRadioReporteGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioReporteGeneralMouseClicked(evt);
            }
        });
        jRadioReporteGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioReporteGeneralActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("Reportes de Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioCategoria)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jRadioStockMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioStockMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioReporteGeneral))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jRadioCategoria)
                .addGap(18, 18, 18)
                .addComponent(jRadioProveedor)
                .addGap(18, 18, 18)
                .addComponent(jRadioTipo)
                .addGap(18, 18, 18)
                .addComponent(jRadioStockMin)
                .addGap(18, 18, 18)
                .addComponent(jRadioStockMax)
                .addGap(18, 18, 18)
                .addComponent(jRadioReporteGeneral)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, 215, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
        String seleccionar = (String) jComboBox1.getSelectedItem();

        if (jRadioStockMax.isSelected()) {
            controllerReportes.ejecutarReporteGeneralStockMax();

        } else if (jRadioStockMin.isSelected()) {
            controllerReportes.ejecutarReporteGeneralStockMin();

        } else if (jRadioTipo.isSelected()) {
            if (jComboBox1.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Seleccion un tipo de producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                controllerReportes.reportesProductoTipo(seleccionar);
            }
        } else if (jRadioProveedor.isSelected()) {
            if (jComboBox1.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Seleccion un Proveedor", "Advertencia", JOptionPane.WARNING_MESSAGE);

            } else {
                controllerReportes.reportesProductoProveedores(seleccionar);
            }

        } else if (jRadioCategoria.isSelected()) {
            if (jComboBox1.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Seleccion una Categoria", "Advertencia", JOptionPane.WARNING_MESSAGE);

            } else {
                controllerReportes.reportesProductoCategorias(seleccionar);
            }
        } else if (jRadioReporteGeneral.isSelected()) {
            controllerReportes.ejecutarReporteGeneralProductos();
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Reportes reportes = new Reportes(usuario);
        reportes.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioTipoMouseClicked
        // TODO add your handling code here:
        controllerProducto.fillCombotTipo_producto(jComboBox1);
        jComboBox1.setEnabled(true);
    }//GEN-LAST:event_jRadioTipoMouseClicked

    private void jRadioProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioProveedorMouseClicked
        // TODO add your handling code here:
        proveedorController.consultarProveedores(jComboBox1);
        jComboBox1.setEnabled(true);
    }//GEN-LAST:event_jRadioProveedorMouseClicked

    private void jRadioCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioCategoriaMouseClicked
        // TODO add your handling code here:
        controllerProducto.fillComboCategoria(jComboBox1);
        jComboBox1.setEnabled(true);
    }//GEN-LAST:event_jRadioCategoriaMouseClicked

    private void jRadioCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioCategoriaActionPerformed

    private void jRadioProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioProveedorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioProveedorActionPerformed

    private void jRadioStockMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioStockMinMouseClicked
        // TODO add your handling code here:
        jComboBox1.setEnabled(false);
    }//GEN-LAST:event_jRadioStockMinMouseClicked

    private void jRadioStockMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioStockMaxMouseClicked
        // TODO add your handling code here:
        jComboBox1.setEnabled(false);
    }//GEN-LAST:event_jRadioStockMaxMouseClicked

    private void jRadioReporteGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioReporteGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioReporteGeneralActionPerformed

    private void jRadioReporteGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioReporteGeneralMouseClicked
        // TODO add your handling code here:
        jComboBox1.setEnabled(false);
    }//GEN-LAST:event_jRadioReporteGeneralMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioCategoria;
    private javax.swing.JRadioButton jRadioProveedor;
    private javax.swing.JRadioButton jRadioReporteGeneral;
    private javax.swing.JRadioButton jRadioStockMax;
    private javax.swing.JRadioButton jRadioStockMin;
    private javax.swing.JRadioButton jRadioTipo;
    // End of variables declaration//GEN-END:variables
}
