/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

/**
 *
 * @author Alexis
 */
public class TallerView extends javax.swing.JFrame {

    /**
     * Creates new form tiendaView
     */
    public TallerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rSButtonMetro1 = new com.ortometh.RSbuttom.RSButtonMetro();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSButtonMetro2 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro3 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro4 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro5 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro7 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro9 = new com.ortometh.RSbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 98, 158));
        jLabel1.setText("TALLER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 237, -1, -1));

        rSButtonMetro1.setBackground(new java.awt.Color(144, 67, 96));
        rSButtonMetro1.setText("PEDIDOS");
        rSButtonMetro1.setColorNormal(new java.awt.Color(144, 67, 96));
        rSButtonMetro1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 197, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 98, 158));
        jLabel4.setText("PROVEEDORES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 202, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(67, 98, 158));
        jLabel5.setText("PACIENTES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 202, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("CERRAR SESION");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 202, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(67, 98, 158));
        jLabel7.setText("CLINICAS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 202, -1, -1));

        rSButtonMetro2.setBackground(new java.awt.Color(105, 145, 59));
        rSButtonMetro2.setText("CORTE DE CAJA");
        rSButtonMetro2.setColorNormal(new java.awt.Color(105, 145, 59));
        rSButtonMetro2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 197, 80));

        rSButtonMetro3.setBackground(new java.awt.Color(40, 25, 25));
        rSButtonMetro3.setText("EXITENCIAS");
        rSButtonMetro3.setColorNormal(new java.awt.Color(40, 25, 25));
        rSButtonMetro3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(rSButtonMetro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 200, 80));

        rSButtonMetro4.setBackground(new java.awt.Color(193, 144, 65));
        rSButtonMetro4.setText("LISTA DE PRECIOS");
        rSButtonMetro4.setColorNormal(new java.awt.Color(193, 144, 65));
        rSButtonMetro4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(rSButtonMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 200, 80));

        rSButtonMetro5.setBackground(new java.awt.Color(49, 30, 46));
        rSButtonMetro5.setText("ENTREGAS");
        rSButtonMetro5.setColorNormal(new java.awt.Color(49, 30, 46));
        rSButtonMetro5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 200, 80));

        rSButtonMetro7.setBackground(new java.awt.Color(90, 55, 32));
        rSButtonMetro7.setText("COMPRAS A PROVEEDORES");
        rSButtonMetro7.setColorNormal(new java.awt.Color(90, 55, 32));
        getContentPane().add(rSButtonMetro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 200, 80));

        rSButtonMetro9.setBackground(new java.awt.Color(34, 51, 48));
        rSButtonMetro9.setText("AJUSTES DE INVENTARIO");
        rSButtonMetro9.setColorNormal(new java.awt.Color(34, 51, 48));
        getContentPane().add(rSButtonMetro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 200, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TallerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TallerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TallerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TallerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TallerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro1;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro2;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro3;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro4;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro5;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro7;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro9;
    // End of variables declaration//GEN-END:variables
}
