/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.model.UsuarioLogin;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;



/**
 *
 * @author Alexis
 */
public class TiendaView extends javax.swing.JFrame {

    /**
     * Creates new form TiendaView
     */
    public static UsuarioLogin usuario;
    public TiendaView() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdUserLogin.setVisible(false);
    }
    
    public TiendaView(UsuarioLogin user) {
        initComponents();
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Tienda");
        
        lblTienda.requestFocus();
        this.usuario = user;
        System.out.println("Id Usuario Login " + user.getIdUserLog());
        txtIdUserLogin.setText(String.valueOf(user.getIdUserLog()));
        this.setLocationRelativeTo(null);
        txtIdUserLogin.setVisible(false);
        if(usuario.getIdPrivilegio() == 2){
            btnCorteCaja.setVisible(false);
        } 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTienda = new javax.swing.JLabel();
        rSButtonMetro1 = new com.ortometh.RSbuttom.RSButtonMetro();
        jLabel6 = new javax.swing.JLabel();
        rSButtonMetro2 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro3 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro4 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro5 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro6 = new com.ortometh.RSbuttom.RSButtonMetro();
        rSButtonMetro7 = new com.ortometh.RSbuttom.RSButtonMetro();
        txtIdUserLogin = new javax.swing.JTextField();
        btnCorteCaja = new com.ortometh.RSbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        lblTienda.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTienda.setForeground(new java.awt.Color(67, 98, 158));
        lblTienda.setText("TIENDA");
        getContentPane().add(lblTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 237, -1, -1));

        rSButtonMetro1.setBackground(new java.awt.Color(144, 67, 96));
        rSButtonMetro1.setText("VENDER");
        rSButtonMetro1.setColorNormal(new java.awt.Color(144, 67, 96));
        rSButtonMetro1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 197, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("CERRAR SESIÓN");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 202, -1, -1));

        rSButtonMetro2.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonMetro2.setText("REPORTES");
        rSButtonMetro2.setColorNormal(new java.awt.Color(102, 102, 102));
        rSButtonMetro2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 200, 80));

        rSButtonMetro3.setBackground(new java.awt.Color(40, 25, 25));
        rSButtonMetro3.setText("PROVEEDORES");
        rSButtonMetro3.setColorNormal(new java.awt.Color(40, 25, 25));
        rSButtonMetro3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro3ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonMetro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 200, 80));

        rSButtonMetro4.setBackground(new java.awt.Color(193, 144, 65));
        rSButtonMetro4.setText("PRODUCTOS");
        rSButtonMetro4.setColorNormal(new java.awt.Color(193, 144, 65));
        rSButtonMetro4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 200, 80));

        rSButtonMetro5.setBackground(new java.awt.Color(49, 30, 46));
        rSButtonMetro5.setText("DEVOLUCIONES");
        rSButtonMetro5.setColorNormal(new java.awt.Color(49, 30, 46));
        rSButtonMetro5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 200, 80));

        rSButtonMetro6.setBackground(new java.awt.Color(139, 96, 59));
        rSButtonMetro6.setText("CLIENTES");
        rSButtonMetro6.setColorNormal(new java.awt.Color(139, 96, 59));
        rSButtonMetro6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 200, 80));

        rSButtonMetro7.setBackground(new java.awt.Color(90, 55, 32));
        rSButtonMetro7.setText("APARTADOS");
        rSButtonMetro7.setColorNormal(new java.awt.Color(90, 55, 32));
        rSButtonMetro7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonMetro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro7ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonMetro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 200, 80));
        getContentPane().add(txtIdUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 50, -1));

        btnCorteCaja.setBackground(new java.awt.Color(105, 145, 59));
        btnCorteCaja.setText("CORTE DE CAJA");
        btnCorteCaja.setColorNormal(new java.awt.Color(105, 145, 59));
        btnCorteCaja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteCajaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCorteCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 197, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        try {
            // TODO add your handling code here:
            ClientesCRUD cd = new ClientesCRUD(usuario, "t");
            cd.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(TiendaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        Venta b = new Venta(usuario);
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro3ActionPerformed
        // PROVEEDORES
        ProveedoresView pv = new ProveedoresView(usuario);
        pv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonMetro3ActionPerformed

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed
        try {
            // TODO add your handling code here:
            ProductosCRUD pc = new ProductosCRUD(usuario);
            pc.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(TiendaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
        // TODO add your handling code here:
         DevolucionesView dv = new DevolucionesView(usuario);
         dv.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        MenuView mv = new MenuView(usuario);
        mv.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        Reportes reportes = new Reportes(usuario);
        reportes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rSButtonMetro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro7ActionPerformed
        // TODO add your handling code here:
        ConsultaApartadosView ca = new ConsultaApartadosView(usuario);
        ca.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rSButtonMetro7ActionPerformed

    private void btnCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteCajaActionPerformed
        // TODO add your handling code here:
        CorteCajaView cv = new CorteCajaView(usuario);
        cv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCorteCajaActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnCorteCaja;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblTienda;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro1;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro2;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro3;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro4;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro5;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro6;
    private com.ortometh.RSbuttom.RSButtonMetro rSButtonMetro7;
    private javax.swing.JTextField txtIdUserLogin;
    // End of variables declaration//GEN-END:variables
}
