/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.Dao.Conexion1;
import com.ortometh.Dao.UsuarioDaoImpl;
import com.ortometh.controller.Usuario_Controller;
import com.ortometh.model.Encryption;
import com.ortometh.model.Events;
import com.ortometh.model.Usuario;
import com.ortometh.model.UsuarioLogin;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexis
 */
public class UsuariosView extends javax.swing.JFrame {

    /**
     * Creates new form tiendaView
     */
    Usuario_Controller usuarioController = new Usuario_Controller();
    UsuarioDaoImpl usuarioDaoImpl = new UsuarioDaoImpl();
    public static UsuarioLogin usarioLog;
    Events evento = new Events();
    Conexion1 con = new Conexion1();
    private Connection cn = con.getConexion();

    public UsuariosView() {
        initComponents();
        UsuariosView.this.setLocationRelativeTo(null);
        this.setResizable(false);
        //Llenar la tabla de usuarios
        usuarioController.fillComboPrivilegios(jComboBoxPrivilegios);
        txtIdUsuario.setText(String.valueOf(1));
        txtIdUsuarioTabla.setVisible(false);
        txtActions.setText("i");
        btnEliminar.setVisible(false);
        btnNuevo.setVisible(false);
        btnCambiarContraseña.setVisible(true);
        btnRecargar.setVisible(false);
        txtIdUsuario.setVisible(true);

    }

    public void limpiar() {
        txtNombre.setText("");
        txtNombreUsuario.setText("");
        txtTelefono.setText("");
        jComboBoxPrivilegios.setSelectedIndex(0);
        jPasswordContrasena.setText("");
        txtIdUsuarioTabla.setText("");
    }

    public UsuariosView(UsuarioLogin login) { //Utilizamos una sobrecarga de metodos para poder asignarle privilegios al Usuario de acuerdo a su rol
        initComponents();
//        Image icon = new ImageIcon(getClass().getResource("../img/Ortomethlogo1.png")).getImage();
//        setIconImage(icon);
//        this.setTitle("Usuarios"); 
        
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        this.usarioLog = login; //Variable para acceder a los datos de Usuario que inicia sesión
        usuarioController.fillProducts(tablaUsuarios);
        usuarioController.fillComboPrivilegios(jComboBoxPrivilegios);
        txtIdUsuario.setText(String.valueOf(login.getIdUserLog()));
        txtIdUsuarioTabla.setVisible(false);
        txtActions.setText("i");
        btnEliminar.setVisible(false);
        btnNuevo.setVisible(false);
        txtIdUsuario.setVisible(false);
        btnCambiarContraseña.setVisible(true);
        btnRecargar.setVisible(false);
        txtNombreLogin.setText(String.valueOf(login.getNombreUsuario()));
        txtNombreLogin.setVisible(false);
        txtContraseñaParaVerificar.setVisible(false);
        txtActions.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new com.ortometh.RSbuttom.RSButtonMetro();
        jLabel11 = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        btnAgregar = new com.ortometh.RSbuttom.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jComboBoxPrivilegios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        txtIdUsuarioTabla = new javax.swing.JTextField();
        btnBuscar = new com.ortometh.RSbuttom.RSButtonMetro();
        txtActions = new javax.swing.JTextField();
        btnCambiarContraseña = new com.ortometh.RSbuttom.RSButtonMetro();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNuevo = new com.ortometh.RSbuttom.RSButtonMetro();
        btnRecargar = new com.ortometh.RSbuttom.RSButtonMetro();
        txtNombreLogin = new javax.swing.JTextField();
        txtContraseñaParaVerificar = new javax.swing.JPasswordField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jPasswordContrasena = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        btnEliminar.setBackground(new java.awt.Color(231, 50, 116));
        btnEliminar.setText("Eliminar");
        btnEliminar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 100, 20));

        jLabel11.setForeground(new java.awt.Color(67, 98, 158));
        jLabel11.setText("Nombre Usuario ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        labelPassword.setForeground(new java.awt.Color(67, 98, 158));
        labelPassword.setText("Contraseña");
        getContentPane().add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(231, 50, 116));
        btnAgregar.setText("Guardar");
        btnAgregar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 90, 20));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 690, 330));

        jComboBoxPrivilegios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxPrivilegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrivilegiosActionPerformed(evt);
            }
        });
        jComboBoxPrivilegios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBoxPrivilegiosKeyTyped(evt);
            }
        });
        getContentPane().add(jComboBoxPrivilegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 300, 20));

        jLabel1.setForeground(new java.awt.Color(67, 98, 158));
        jLabel1.setText("Privilegios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel6.setForeground(new java.awt.Color(67, 98, 158));
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 50, 20));

        jLabel7.setForeground(new java.awt.Color(67, 98, 158));
        jLabel7.setText("Teléfono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));
        getContentPane().add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 50, -1));
        getContentPane().add(txtIdUsuarioTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 50, -1));

        btnBuscar.setBackground(new java.awt.Color(231, 50, 116));
        btnBuscar.setText("Buscar");
        btnBuscar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnBuscar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 90, 20));
        getContentPane().add(txtActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 570, 50, -1));

        btnCambiarContraseña.setBackground(new java.awt.Color(231, 50, 116));
        btnCambiarContraseña.setText("Cambiar contraseña");
        btnCambiarContraseña.setColorNormal(new java.awt.Color(231, 50, 116));
        btnCambiarContraseña.setColorPressed(new java.awt.Color(38, 86, 186));
        btnCambiarContraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 140, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(67, 98, 158));
        jLabel12.setText("Control de Usuarios");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(67, 98, 158));
        jLabel4.setText("Control de Usuarios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        btnNuevo.setBackground(new java.awt.Color(231, 50, 116));
        btnNuevo.setText("Nuevo");
        btnNuevo.setColorNormal(new java.awt.Color(231, 50, 116));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 90, 20));

        btnRecargar.setBackground(new java.awt.Color(231, 50, 116));
        btnRecargar.setText("Recargar");
        btnRecargar.setColorNormal(new java.awt.Color(231, 50, 116));
        btnRecargar.setColorPressed(new java.awt.Color(38, 86, 186));
        btnRecargar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 140, 20));
        getContentPane().add(txtNombreLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 100, -1));
        getContentPane().add(txtContraseñaParaVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 300, -1));
        getContentPane().add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 300, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 300, -1));

        jPasswordContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordContrasenaKeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 300, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "¿Confirma la eliminación?", "Eliminar usuario", JOptionPane.YES_NO_OPTION);
        System.out.print("Opción: " + confirm);
        if (confirm == 0) {
            String nombreUsuario = txtNombreUsuario.getText();
            usuarioController.eliminar(nombreUsuario);
            usuarioController.Recargar(tablaUsuarios);
            limpiar();
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (txtActions.getText().equals("i")) {
            if (txtNombre.getText().equals("") || jPasswordContrasena.getPassword().equals("") || txtNombreUsuario.getText().equals("") || jComboBoxPrivilegios.getSelectedItem().equals("") || txtTelefono.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Llene todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else if (txtActions.getText().equals(String.valueOf(1))) {
                JOptionPane.showMessageDialog(null, "Está intentando insertar un usuario con datos existentes, debe crear datos nuevos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                limpiar();
            } else {
                String password = new String(jPasswordContrasena.getPassword());
                String newPassword = Encryption.sha1(password);
                String contrasena = (newPassword);
                String nombre = txtNombre.getText();
                String nombreUsuario = txtNombreUsuario.getText();
                String privilegios = jComboBoxPrivilegios.getSelectedItem().toString();
                String telefono = txtTelefono.getText();

                int idUsuario = Integer.parseInt(txtIdUsuario.getText());

                if (jComboBoxPrivilegios.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Seleccione un nivel de Usuario");
                } else {
                    String message = usuarioController.registrar_usuario(nombre, nombreUsuario, contrasena, privilegios, telefono, idUsuario);
                    JOptionPane.showMessageDialog(null, message);
                    usuarioController.Recargar(tablaUsuarios);
                    limpiar();
                }
            }

        } else if (txtActions.getText().equals("m")) {
            if (txtNombre.getText().equals("") || txtNombreUsuario.getText().equals("") || jComboBoxPrivilegios.getSelectedItem().equals("") || txtTelefono.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campos vacíos", "Advertencia", JOptionPane.WARNING_MESSAGE);

//                } else if (txtActions.getText().equals(String.valueOf(1))) {
//                JOptionPane.showMessageDialog(null, "Está intentando insertar un Usuario con datos existentes, debe crear datos nuevos", "Advertencia", JOptionPane.WARNING_MESSAGE);
//                limpiar();
            } else {

                String password = new String(jPasswordContrasena.getPassword());
                String clave = new String(txtContraseñaParaVerificar.getPassword());
                String newPassword = Encryption.sha1(password);
                String contrasena = (newPassword);
                String nombre = txtNombre.getText();
                String nombreUsuario = txtNombreUsuario.getText();
                String privilegios = jComboBoxPrivilegios.getSelectedItem().toString();
                String telefono = txtTelefono.getText();
                int idUsuario = Integer.parseInt(txtIdUsuario.getText());
                int idUsuarioTabla = Integer.parseInt(txtIdUsuarioTabla.getText());

                if (jComboBoxPrivilegios.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Seleccione un nivel de Usuario");

                } else {
                    if (!password.equals(clave)) {
                        String messages = usuarioController.modificarConContraseña(idUsuarioTabla, nombre, nombreUsuario, newPassword, privilegios, telefono, idUsuario);
                        JOptionPane.showMessageDialog(null, messages);
                        usuarioController.Recargar(tablaUsuarios);
                        limpiar();

                    } else {
                        String messages = usuarioController.modificar(idUsuarioTabla, nombre, nombreUsuario, privilegios, telefono, idUsuario);
                        JOptionPane.showMessageDialog(null, messages);
                        usuarioController.Recargar(tablaUsuarios);
                        limpiar();
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked

        btnEliminar.setVisible(true);
        btnNuevo.setVisible(true);
        btnCambiarContraseña.setVisible(false);
        jPasswordContrasena.setVisible(true);
        labelPassword.setVisible(true);
        btnRecargar.setVisible(true);
        btnCambiarContraseña.setVisible(true);

        int row = tablaUsuarios.getSelectedRow();

        int idUser = (int) tablaUsuarios.getValueAt(row, 0);
        String nombre = (String) tablaUsuarios.getValueAt(row, 1);
        String nombreUsuario = (String) tablaUsuarios.getValueAt(row, 2);
        String telefono = (String) tablaUsuarios.getValueAt(row, 3);
        String privilegios = (String) tablaUsuarios.getValueAt(row, 4);
        String tipoUsuario = String.valueOf(privilegios);
        String ultima_sesion = (String) tablaUsuarios.getValueAt(row, 5);
        ArrayList<Usuario> con = usuarioDaoImpl.getContraseñaDeUsuario(nombreUsuario);
        txtNombre.setText(nombre);
        txtNombreUsuario.setText(nombreUsuario);
        txtTelefono.setText(telefono);
        jComboBoxPrivilegios.setSelectedItem(privilegios);
        txtIdUsuarioTabla.setText(String.valueOf(idUser));
        txtActions.setText("m");

    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MenuView mv = new MenuView(usarioLog);
        mv.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jComboBoxPrivilegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrivilegiosActionPerformed
    }//GEN-LAST:event_jComboBoxPrivilegiosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombreUsuario = txtNombreUsuario.getText();
        if (txtNombreUsuario.getText() != null) {
            usuarioController.filtrarUsuario(tablaUsuarios, nombreUsuario);
        } else {
            JOptionPane.showMessageDialog(null, "Campo vacio");
        }
        limpiar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jComboBoxPrivilegiosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxPrivilegiosKeyTyped
    }//GEN-LAST:event_jComboBoxPrivilegiosKeyTyped

    private void btnCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContraseñaActionPerformed
        UsuariosView UsuariosView = new UsuariosView();
        this.setVisible(false);
        CambiarContraseñaView cambiarContraseñaView = new CambiarContraseñaView(usarioLog);
        cambiarContraseñaView.setVisible(true);

    }//GEN-LAST:event_btnCambiarContraseñaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtActions.setText("i");
        limpiar();
        btnEliminar.setVisible(false);
        btnNuevo.setVisible(false);
        btnCambiarContraseña.setVisible(false);
        jPasswordContrasena.setVisible(true);
        labelPassword.setVisible(true);
        btnRecargar.setVisible(false);
        btnCambiarContraseña.setVisible(true);

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        usuarioController.Recargar(tablaUsuarios);
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        evento.textKeyPress(evt);
        evento.upperFisrtLetter(evt, txtNombre);
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        evento.numberKeyPress(evt);
        evento.limitCharacters(evt, txtTelefono, 15);
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void jPasswordContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordContrasenaKeyTyped
        evento.textVarcharKeyPress(evt);
    }//GEN-LAST:event_jPasswordContrasenaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ortometh.RSbuttom.RSButtonMetro btnAgregar;
    private com.ortometh.RSbuttom.RSButtonMetro btnBuscar;
    private com.ortometh.RSbuttom.RSButtonMetro btnCambiarContraseña;
    private com.ortometh.RSbuttom.RSButtonMetro btnEliminar;
    private com.ortometh.RSbuttom.RSButtonMetro btnNuevo;
    private com.ortometh.RSbuttom.RSButtonMetro btnRecargar;
    private javax.swing.JComboBox<String> jComboBoxPrivilegios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JPasswordField jPasswordContrasena;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtActions;
    public static javax.swing.JPasswordField txtContraseñaParaVerificar;
    public static javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtIdUsuarioTabla;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreLogin;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
