/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ortometh.viewMain;

import com.ortometh.Dao.VentaDaoImpl;
import com.ortometh.controller.ProductoController;
import com.ortometh.controller.VentaController;
import com.ortometh.model.Events;
import com.ortometh.model.UsuarioLogin;
import static com.ortometh.viewMain.BuscarProductoView.txtclave;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jacQu
 */
public class Venta extends javax.swing.JFrame {

    Events evento = new Events();
    VentaController venController = new VentaController();
    ProductoController productoController = new ProductoController();
    VentaDaoImpl ventaDaoImpl = new VentaDaoImpl();

    ArrayList<Integer> productos = new ArrayList<>();

    //variable de usuario
    public static UsuarioLogin usuario;
    public static String tipo_venta = "Tienda";
    int id_venta;
    //contar productos
    int cantidad_productos = 0;
    //total importe
    Double total_importe;
    int id_cliente = 1;
    //subtotal
    Double subtotal = 00.00;
    //DecimalFormat df = new DecimalFormat("##.##");
    int id_productoMod;
    int cantidadMod;
    String clave_productoMod;
    
    /**
     * Creates new form venta
     */
    public Venta(UsuarioLogin user){
        initComponents();
        

        //diseño de vista
        this.setLocationRelativeTo(null);
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        txtNombreCliente.setHorizontalTextPosition(txtCodigoProducto.CENTER);
        txtNombreCliente.setHorizontalAlignment((int) txtCodigoProducto.CENTER_ALIGNMENT);
        txtCodigoProducto.requestFocus();
        txtId_usuario.setVisible(false);
        txtId_Cliente.setVisible(false);
        txtIdcliente.setVisible(false);
        stock.setVisible(false);
        txtId_producto1.setVisible(false);
        //INICIA DATOS DEL USUARIO
        this.usuario = user;
        System.out.println("Id Usuario Login venta " + usuario.getIdUserLog());
        contar_piezas();//consulta
        importe_total();//consulta
        subtotal();
        
        //LLENAR TABLA DE INFORMACION DEL PRODUCTO
        if (txtCodigoProducto.getText() != "") {
            venController.fillProductos(tablaProductos, id_venta, txtCodigoProducto.getText());
        }
    }

    private Venta() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void datos_Venta() throws SQLException {
        ResultSet rs = ventaDaoImpl.seleccionar_id(id_venta);
        while (rs.next()) {
            txtNoVenta.setText(String.valueOf(rs.getInt("id_venta")));
            txtFecha.setText(String.valueOf(rs.getDate("fecha_venta")));
            txttotal.setText(String.valueOf(rs.getDouble("importe")));
        }
    }

//    public void datos_usuario() {
//        txtId_usuario.setText(String.valueOf(usuario.getIdUserLog()));
//        txtNombreUsuario.setText(usuario.getNombreUsuario().toUpperCase());
//        txtNombreUsuario.setHorizontalTextPosition(txtCodigoProducto.CENTER);
//        txtNombreUsuario.setHorizontalAlignment((int) txtCodigoProducto.CENTER_ALIGNMENT);
//
//    }
    public void contar_piezas() {
        cantidad_productos = venController.contar_venta(id_venta);
        txtPiezas.setText(String.valueOf(cantidad_productos));
    }

    public void subtotal() {
        subtotal = venController.subtotal(id_venta);
        txtsubtotal.setText(String.valueOf(String.format("%.2f", subtotal)));
    }

    public void importe_total() {
        total_importe = venController.seleccionar_importe(id_venta);
        txttotal.setText(String.valueOf(String.format("%.2f", total_importe)));
    }

    public void descuento() {
        double descuento = subtotal - total_importe;
        // double descuento = Double.parseDouble(txtsubtotal.getText()) - Double.parseDouble(txttotal.getText());
        txtdescuento.setText(String.valueOf(String.format("%.2f", descuento)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNoVenta = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        txtCodigoProducto = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txttotal = new javax.swing.JLabel();
        txtdescuento = new javax.swing.JLabel();
        txtPiezas = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JLabel();
        txtId_usuario = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtNombreCliente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId_Cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdcliente = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtId_producto1 = new javax.swing.JTextField();
        btnagregar1 = new javax.swing.JButton();
        btnagregar2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        stock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1054, 706));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1050, 10));

        jLabel14.setForeground(new java.awt.Color(67, 98, 158));
        jLabel14.setText("No. de Venta");

        jLabel15.setForeground(new java.awt.Color(67, 98, 158));
        jLabel15.setText("Fecha");

        txtNoVenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(txtNoVenta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel15)))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoVenta)
                    .addComponent(txtFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 40));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio Unitario", "Descuento", "Precio Neto", "Importe"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        tablaProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaProductosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1030, 200));

        txtCodigoProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyReleased(evt);
            }
        });
        getContentPane().add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 170, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/icons8-búsqueda-40.png"))); // NOI18N
        jButton3.setText("Buscar Producto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 180, 40));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(67, 98, 158));
        jLabel17.setText("Descuento");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 110, 37));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(67, 98, 158));
        jLabel18.setText("Total: ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 80, 37));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(67, 98, 158));
        jLabel19.setText("Subtotal");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 100, 37));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(67, 98, 158));
        jLabel20.setText("Piezas");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 80, 37));

        btnagregar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/icons8-eliminar-40.png"))); // NOI18N
        btnagregar.setText("Cancelar venta");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 160, 40));

        jButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/icons8-monedas-40.png"))); // NOI18N
        jButton2.setText("Cobrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, -1, 40));

        txttotal.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 160, 40));
        getContentPane().add(txtdescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 550, 90, 20));
        getContentPane().add(txtPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 60, 20));
        getContentPane().add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 90, 20));

        txtId_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtId_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 60, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_BOTTOM));

        txtNombreCliente.setText("PUBLICO GENERAL G P");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 260, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/icons8-encuentra-hombre-usuario-40.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));
        getContentPane().add(txtId_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/icons8-añadir-usuario-masculino-40.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/header.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1050, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/footer.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, -1, 100));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(67, 98, 158));
        jLabel21.setText("Código del Producto: ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, 37));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(67, 98, 158));
        jLabel22.setText("Cantidad");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 60, 30));

        txtIdcliente.setDoubleBuffered(true);
        txtIdcliente.setMinimumSize(new java.awt.Dimension(0, 18));
        getContentPane().add(txtIdcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtCantidad.setText("1");
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 80, -1));

        txtDescuento.setText("00.00");
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyReleased(evt);
            }
        });
        getContentPane().add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 80, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(67, 98, 158));
        jLabel23.setText("Descuento %");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 80, 30));

        txtId_producto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_producto1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtId_producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 60, -1));

        btnagregar1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnagregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/icons8-editar-40.png"))); // NOI18N
        btnagregar1.setText("Agregar ");
        btnagregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 180, 40));

        btnagregar2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnagregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/icons8-marca-de-verificación-40.png"))); // NOI18N
        btnagregar2.setText("Iniciar venta");
        btnagregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 150, 40));

        jButton4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ortometh/img/icons8-menos-40.png"))); // NOI18N
        jButton4.setText("Eliminar Producto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 180, 40));
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtId_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_usuarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        BuscarProductoView bProductoView = null;
        try {
            bProductoView = new BuscarProductoView(0);
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
        bProductoView.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "¿Desea cancelar la venta?", "Venta", JOptionPane.YES_NO_OPTION);
        System.out.println("Opcion: " + confirm);
        if (confirm == 0) {
            venController.cancelar_venta(id_venta, usuario.getIdUserLog());
            TiendaView tiView = new TiendaView(usuario);
            tiView.setVisible(true);
            this.dispose();

        } else {

        }

    }//GEN-LAST:event_btnagregarActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
//        buscarClienteView buClienteView = null;
//        try {
//            buClienteView = new buscarClienteView();
//        } catch (SQLException ex) {
//            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        buClienteView.setVisible(true);
        /*No cerrar la ventana de Venta, ya que cambiaria el id*/
        ClientesCRUD cc = null;
        try {
            cc = new ClientesCRUD(usuario, "v");
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
        ClientesCRUD.btnReporteFisico.setVisible(false);
        cc.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        ClientesCRUD cc = null;
        try {
            cc = new ClientesCRUD(usuario, "v");
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
        ClientesCRUD.btnReporteFisico.setVisible(false);
        cc.setVisible(true);

        /* No cerrar la vista de Venta porque cambiaria el id de Venta*/
    }//GEN-LAST:event_jLabel3MouseClicked

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
    int fila = tablaProductos.getSelectedRow();
        ResultSet rs2 = null;
        id_productoMod = 0;
         if(tablaProductos.getValueAt(fila, 2).toString().equals("")  || tablaProductos.getValueAt(fila, 0).toString().equals("")){
                JOptionPane.showMessageDialog(null, "Hay campos vacios en la fila");
            }else{
        cantidadMod = Integer.parseInt(tablaProductos.getValueAt(fila, 2).toString());
        clave_productoMod = tablaProductos.getValueAt(fila, 0).toString();

        try {
            rs2 = ventaDaoImpl.datos_producto(clave_productoMod);
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while (rs2.next()) {
                try {
                    id_productoMod = rs2.getInt("id_producto");
                } catch (SQLException ex) {
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }

         }


    }//GEN-LAST:event_tablaProductosMouseClicked

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtCodigoProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyReleased
        evento.limitCharacters(evt, txtCodigoProducto, 8);
    }//GEN-LAST:event_txtCodigoProductoKeyReleased

    private void txtDescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyReleased
        evento.numberDecimalKeyPress(evt, txtDescuento);
    }//GEN-LAST:event_txtDescuentoKeyReleased

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        evento.numberKeyPress(evt);
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "¿Desea terminar la venta?", "Venta", JOptionPane.YES_NO_OPTION);
        System.out.println("Opcion: " + confirm);
        if (confirm == 0) {
            Caja caja = new Caja(usuario, id_venta);
            caja.TXRMONTOTOTAL.setText(String.valueOf(total_importe));
            caja.txtmonto.setText(String.valueOf(total_importe));
            caja.setVisible(true);
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        venController.cancelar_venta(id_venta, usuario.getIdUserLog());
        TiendaView tv = new TiendaView(usuario);
        tv.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void txtId_producto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_producto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_producto1ActionPerformed

    private void btnagregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar1ActionPerformed
        
   boolean busqueda=false;
       
        if (txtNoVenta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No se ha iniciado la  venta");
        } 
        else {
             
            txtNombreCliente.setEnabled(false);
            jLabel5.setVisible(false);
            jLabel3.setVisible(false);
            if (txtCodigoProducto.getText().equals("") || txtCantidad.getText().equals("") || txtDescuento.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Hay campos vacíos");
            } 
            else 
            {
                int stock_actual=0;
             int stock_minimo=0;
                    int id_producto = 0;
                    String descripcion;
                    String clave_producto = "";
                    double precio = 0;
                    
                    ResultSet rs2;
                    try {
                        rs2 = ventaDaoImpl.datos_producto(txtCodigoProducto.getText());
                        while (rs2.next()) {
                            id_producto = rs2.getInt("id_producto");
                            clave_producto = rs2.getString("clave_producto");
                            descripcion = rs2.getString("descripcion");
                            precio = rs2.getDouble("precio_venta");
                            stock_actual= rs2.getInt("stock");
                            stock_minimo = rs2.getInt("stock_min");
                        }
                        Venta.stock.setText(String.valueOf(stock_actual));
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
                    
                   int cant = Integer.parseInt(txtCantidad.getText());
                int stock = Integer.parseInt(Venta.stock.getText());
                if (cant > stock) {
                    JOptionPane.showMessageDialog(null, "No se cuenta con esa cantidad de producto");
                } 
                else {
                    for (int i = 0; i < productos.size(); i++) {
                        if (productos.get(i) == id_producto) {
                           busqueda = true;
                        }
                    }    
                    if(busqueda==true){
                        JOptionPane.showMessageDialog(null, "El producto ya esta agregado,se recomienda modificar la cantidad");
                    }  else{
                            if (venController.llenar_venta(Integer.parseInt(txtId_Cliente.getText()), id_venta, id_producto, Integer.parseInt(txtCantidad.getText()), Double.parseDouble(txtDescuento.getText()), usuario.getIdUserLog())) {
                                try {
                                    venController.reFillProveedores(tablaProductos, id_venta, txtCodigoProducto.getText());
                                } catch (SQLException ex) {
                                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                contar_piezas();
                                importe_total();
                                subtotal();
                                descuento();
                                productos.add(id_producto);
                            } else {
                                JOptionPane.showMessageDialog(null, "No se cuenta con esa cantidad en stock");
                            }
                        }
                        txtCodigoProducto.setText("");
                        txtDescuento.setText("00.00");
                        txtCantidad.setText("1");
                }
                 if(stock_actual <= stock_minimo){
            JOptionPane.showMessageDialog(null, "Se esta en  el stock minimo");
            }
            }
            
        }
    }//GEN-LAST:event_btnagregar1ActionPerformed

    private void btnagregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar2ActionPerformed
        //this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        if (txtId_Cliente.getText().equals("")) {
            int confirm = JOptionPane.showConfirmDialog(null, "¿El cliente será publico general?", "Venta", JOptionPane.YES_NO_OPTION);
            System.out.println("Opcion: " + confirm);
            if (confirm == 0) {
                txtId_Cliente.setText("1");
                id_cliente = Integer.parseInt(txtId_Cliente.getText());
                System.out.println(venController.iniciar_venta(tipo_venta, usuario.getIdUserLog(), id_cliente));
                try {
                    //SELECCIONAR EL ID DE LA VENTA
                    id_venta = venController.seleccionar_idVenta();
                } catch (SQLException ex) {
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    //DATOS DE LA VENTA
                    datos_Venta();
                    // txtNombreCliente.setText("PUBLICO GENERAL P G");
                } catch (SQLException ex) {
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                }
                btnagregar2.setVisible(false);
                jLabel5.setVisible(false);
                jLabel3.setVisible(false);
                txtNombreCliente.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione el cliente para la venta");
            }
        } else {
            id_cliente = Integer.parseInt(txtId_Cliente.getText());
            System.out.println(venController.iniciar_venta(tipo_venta, usuario.getIdUserLog(), id_cliente));
            try {
                //SELECCIONAR EL ID DE LA VENTA
                id_venta = venController.seleccionar_idVenta();
            } catch (SQLException ex) {
                Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                //DATOS DE LA VENTA
                datos_Venta();
                // txtNombreCliente.setText("PUBLICO GENERAL P G");
            } catch (SQLException ex) {
                Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
            }
            btnagregar2.setVisible(false);
            jLabel5.setVisible(false);
            jLabel3.setVisible(false);
            txtNombreCliente.setEnabled(false);
        }
    }//GEN-LAST:event_btnagregar2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int fila = tablaProductos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
             int confirm = JOptionPane.showConfirmDialog(null, "¿Confirma la eliminación?", "Eliminar producto", JOptionPane.YES_NO_OPTION);
                System.out.println("Opcion: " + confirm);
                if (confirm == 0) {
                    try {
            if (venController.eliminar_producto(id_venta, id_productoMod)) {
                JOptionPane.showMessageDialog(null, "Se a eliminado el producto");
                venController.reFillProveedores(tablaProductos, id_venta, clave_productoMod);
                for (int i = 0; i < productos.size(); i++) {
                        if (productos.get(i) == id_productoMod) {
                           productos.remove(i);
                        }
                } 
                contar_piezas();//consulta
                importe_total();//consulta
                subtotal();
                descuento();//resta
                
            } else {
                JOptionPane.showMessageDialog(null, "No se a podido eliminar el producto ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
                }
        }      
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablaProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaProductosKeyPressed
      int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            int fila = tablaProductos.getSelectedRow();
            ResultSet rs2 = null;
            id_productoMod = 0;
            if(tablaProductos.getValueAt(fila, 2).toString().equals("")  || tablaProductos.getValueAt(fila, 0).toString().equals("")){
                JOptionPane.showMessageDialog(null, "Hay campos vacios en la fila");
            }else{
                
            
            cantidadMod = Integer.parseInt(tablaProductos.getValueAt(fila, 2).toString());
            clave_productoMod = tablaProductos.getValueAt(fila, 0).toString();

            try {
                rs2 = ventaDaoImpl.datos_producto(clave_productoMod);
            } catch (SQLException ex) {
                Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                while (rs2.next()) {
                    try {
                        id_productoMod = rs2.getInt("id_producto");
                    } catch (SQLException ex) {
                        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.err.println(cantidadMod);
            System.err.println(id_productoMod);
            System.err.println(cantidadMod);
            if (key == KeyEvent.VK_ENTER) {
                try {
                    if (venController.cancelar_producto(id_venta, id_productoMod, cantidadMod)) {
                        JOptionPane.showMessageDialog(null, "Se a actualizado la cantidad correctamente");
                        venController.reFillProveedores(tablaProductos, id_venta, clave_productoMod);
                        contar_piezas();//consulta
                        importe_total();//consulta
                        subtotal();
                        descuento();//resta
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        }
    }//GEN-LAST:event_tablaProductosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnagregar1;
    private javax.swing.JButton btnagregar2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField stock;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JLabel txtFecha;
    public static javax.swing.JTextField txtId_Cliente;
    public static javax.swing.JTextField txtId_producto1;
    private javax.swing.JTextField txtId_usuario;
    private javax.swing.JTextField txtIdcliente;
    private javax.swing.JLabel txtNoVenta;
    public static javax.swing.JLabel txtNombreCliente;
    private javax.swing.JLabel txtPiezas;
    private javax.swing.JLabel txtdescuento;
    private javax.swing.JLabel txtsubtotal;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
